### ISSUE TITLE
Mapping Arrays of @Reference(idOnly = true)

### ISSUE THREAD

**Issue by mrgoodrich** [MorphiaOrg/morphia#1156]
Hello, is it possible to map `@Reference(idOnly = true)` arrays of objects?  I currently have other `@Reference(idOnly = true)`'s working, but when I try to use an array of them, Morphia errors stating the `@Id` annotation does not exist.  To verify the `@Id` annotation does in fact exist, I changed the type from `MyObject[][][]` to `List<List<List<MyObject>>>`, which succeeded.

Since I'm on a strict deadline with this project, I plan to try using a `transient MyObject[][][]` in the meantime with a `@PrePersist` and a `@PostLoad`, to convert from the required type to what I need.

Is this a problem with my methodology, mapping arrays in Morphia, mapping arrays of DbRefs in Morphia, or mapping three-dimensional arrays in Morphia?

**Comment by mrgoodrich** [comment]
Here's the error for reference:

> ReferenceToUnidentifiable complained about simulator.Evolution.generations : simulator.Evolution.generations is annotated as a @Reference but the [[[Lsimulator.Simulation; class is missing the @Id annotation

**Comment by mrgoodrich** [comment]
Note the `List<List<List<Simulation>>>` worked, but I had to remove the `@Reference(idOnly = true)` due to `NullPointerException`s.  Here's one of the stack traces with `List<List<List<Simulation>>>` and the `@Reference(idOnly = true)`:

```
Exception in thread "main" org.mongodb.morphia.mapping.MappingException: Error mapping field:simulator.Evolution.generationsList
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:984)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593)
	at org.mongodb.morphia.DatastoreImpl.entityToDBObj(DatastoreImpl.java:1362)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:1282)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:775)
	at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:758)
	at simulator.Evolver.advanceEvolution(Evolver.java:37)
	at simulator.Worker.advanceIdleEvolution(Worker.java:65)
	at simulator.Worker.work(Worker.java:92)
	at simulator.Worker.joinSwarm(Worker.java:51)
	at utility.Main.runUtility(Main.java:58)
	at utility.Main.main(Main.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NullPointerException
	at org.mongodb.morphia.mapping.ReferenceMapper.getKey(ReferenceMapper.java:104)
	at org.mongodb.morphia.mapping.ReferenceMapper.addValue(ReferenceMapper.java:79)
	at org.mongodb.morphia.mapping.ReferenceMapper.writeCollection(ReferenceMapper.java:236)
	at org.mongodb.morphia.mapping.ReferenceMapper.toDBObject(ReferenceMapper.java:64)
	at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:869)
	at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982)
```

**Comment by mrgoodrich** [comment]
After extensive testing I'm pretty confident the problem is multi-dimensional collections with dbrefs.

**Comment by evanchooly** [comment]
It's definitely the nesting that's doing it.  Fixing it in 1.x would be a monumental task, I'm afraid.  I'll see what I can do in 2.0, though.
