### ISSUE TITLE
Near query works with error

### ISSUE THREAD

**Issue by abdollahpour** [MorphiaOrg/morphia#1194]
I'm using Morphia 1.3.2 & Java8. I have class like

    @Entity
    public class Gym {

        @Indexed(IndexDirection.GEO2DSPHERE)
        @XmlJavaTypeAdapter(LocationAdapter.class)
        @NotNull
        private Point location;

    }

Query like this work:

    q.field(LOCATION).near(point, distance);

but print out this error in logs:

```
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: java.lang.NullPointerException
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.mongodb.morphia.mapping.Mapper.toMongoObject(Mapper.java:634)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:64)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.mongodb.morphia.query.FieldCriteria.<init>(FieldCriteria.java:31)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.mongodb.morphia.query.StandardGeoFieldCriteria.<init>(StandardGeoFieldCriteria.java:30)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.mongodb.morphia.query.FieldEndImpl.near(FieldEndImpl.java:212)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.mongodb.morphia.query.FieldEndImpl.near(FieldEndImpl.java:26)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at com.wpic.smartgym.facade.GymFacade.page(GymFacade.java:76)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at com.wpic.smartgym.facade.GymFacade$Proxy$_$$_WeldSubclass.page$$super(Unknown Source)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at java.lang.reflect.Method.invoke(Method.java:498)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:51)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:78)
Sep 25 19:51:13 iZ2ze72qolz2be5v4kuyd7Z SocketTest[5797]: at org.hibernate.validator.internal.cdi.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79)
```

I'm not sure if the results are correct too. And another strange thing is if I write query like this (use lat&lng instead of point):

    q.field(LOCATION).near(lat, lng, distance);

It does not work at all and says:

    unable to find index for $geoNear query' on server

**Comment by evanchooly** [comment]
I can't reproduce this on current code.  Please open a new issue on the latest version if the problem persists.
