### ISSUE TITLE
MapKeyDifferentFromString error even though @Embedded

### ISSUE THREAD

**Issue by tjbdev** [MorphiaOrg/morphia#1236]
`MapKeyDifferentFromString complained about package : Maps must be keyed by a simple type (Map<String/Enum/Long/ObjectId/..., ?>); class customObject is not supported as a map key type.`

This is the error that I receive. Is there a way to have a Map with keys of custom objects stored in the database? I have @Embedded above the Map object.

**Comment by CorasConflict** [comment]
I attempted to work around it by just changing the map to an arraylist with a single map object, but I got this:

`java.lang.StackOverflowError
        at org.mongodb.morphia.converters.Converters.getEncoder(Converters.java:265) ~[?:?]
        at org.mongodb.morphia.converters.CustomConverters.getEncoder(CustomConverters.java:53) ~[?:?]
        at org.mongodb.morphia.converters.Converters.getEncoder(Converters.java:296) ~[?:?]
        at org.mongodb.morphia.converters.Converters.hasSimpleValueConverter(Converters.java:185) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:866) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]
        at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]
        at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]
        at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]
        at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]
        at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]
        at org.mongodb.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.writeMappedField(Mapper.java:876) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:982) ~[?:?]
        at org.mongodb.morphia.mapping.Mapper.toDBObject(Mapper.java:593) ~[?:?]`

**Comment by evanchooly** [comment]
This isn't possible at the database layer.  document keys must be string types in the database so there's not much Morphia can do at the mapping layer.
