### ISSUE TITLE
Aggregation throws exception

### ISSUE THREAD

**Issue by Spentas** [MorphiaOrg/morphia#1252]
```java
        AggregationPipeline pipeline = getDs()
            .createAggregation(User.class)
            .group(grouping("count", accumulator("$sum", 1)));

        final DBObject group = ((AggregationPipelineImpl) pipeline).getStages().get(0);
        Assert.assertNull(group.get("_id"));

        pipeline.aggregate(User.class);
```

```java
com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:257)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:253)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:431)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:253)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:67)
	at com.mongodb.Mongo.execute(Mongo.java:836)
	at com.mongodb.Mongo$2.execute(Mongo.java:823)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1452)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1415)
	at org.mongodb.morphia.aggregation.AggregationPipelineImpl.aggregate(AggregationPipelineImpl.java:81)
	at org.mongodb.morphia.aggregation.AggregationPipelineImpl.aggregate(AggregationPipelineImpl.java:73)
	at org.mongodb.morphia.aggregation.AggregationPipelineImpl.aggregate(AggregationPipelineImpl.java:63)
```

**Comment by madmuffin1** [comment]
You are missing the `AggregationOptions` param in the  `org.mongodb.morphia.aggregation.AggregationPipeline#aggregate(java.lang.Class<U>, com.mongodb.AggregationOptions)` call. 

Use something similar to ` AggregationOptions opts = builder().outputMode(AggregationOptions.OutputMode.CURSOR).build();` to make it work.

Morphia still defaults to `OutputMode.INLINE`, but MongoDB dropped support for inline output since 3.6

**Comment by zarubto4** [comment]
Hi @madmuffin1 , your solution is not working. And I have no idea why. 

     Iterator<QueryResultStats> aggregate = ModelMongo_ThingsMobile_CRD.find
                    .createAggregation()
                    .group(
                            "msisdn",
                            Group.grouping(
                                    "consumption_total",
                                    Group.sum( "cdr_traffic")
                            )
                    )
                    .out(
                            QueryResultStats.class,
                            AggregationOptions
                                    .builder()
                                    .allowDiskUse(false)
                                    .maxTime( 5000 , TimeUnit.SECONDS)
                                    .outputMode(AggregationOptions.OutputMode.CURSOR)
                                    .build()
                    );


as you can see, i set outputMode(AggregationOptions.OutputMode.CURSOR), but still get Error 

```
Exception type: com.mongodb.MongoCommandException
Exception message: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument'
```

**Comment by evanchooly** [comment]
On `master` and mongo server 4.0.3, I don't get this error.  What versions are you using where you see this?  It might be too late to follow up and for that I apologize.  I'm trying to close out the backlog but afraid I've missed the window on some of these.
