### ISSUE TITLE
When I am running npm, I am facing this error

### ISSUE THREAD

**Issue by niranjanreddy891** [MorphiaOrg/morphia#1257]
When I am running `npm start` from terminal, I get this error
```
niranjan@niranjan:~/Documents/catalog-service/build/code/runtime$ npm start

> src@0.0.0 start /home/niranjan/Documents/catalog-service/build/code/runtime
> node ./bin/www

(node:20997) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
Error connecting
{ MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (/home/niranjan/Documents/catalog-service/build/code/runtime/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at Pool.emit (events.js:180:13)
    at Connection.<anonymous> (/home/niranjan/Documents/catalog-service/build/code/runtime/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:272:13)
    at Connection.emit (events.js:180:13)
    at Socket.<anonymous> (/home/niranjan/Documents/catalog-service/build/code/runtime/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:272:13)
    at Socket.emit (events.js:180:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:178:19)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {} }

```
I am using Ubuntu 16.04 with Mongodb-4.0.2 version installed.

**Comment by evanchooly** [comment]
This issue is unrelated to Morphia.  You should ask on the mongodb-users mailing-list.
