### ISSUE TITLE
StackOverflowException when saving entity

### ISSUE THREAD

**Issue by wilmervanheerde** [MorphiaOrg/morphia#1333]
- Morphia version 1.4.1
- JDK version 1.8.0_181
- Mongodb version 4.0.6

I'm getting an StackOverflowException everytime I try to save this entity. Seems something to do with the **items** field. I'm getting this stacktrace regardless of whether I register any type converters for the ItemStack type. It doesn't change anything.

I've tried to make a workaround with class InventoryContentListeners containing @PostLoad and @PrePersist listeners that manually serialize the field into another field (serializedContent), but that doesn't seem to fix it. 

For reference, the source of ItemStack is https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/inventory/ItemStack.java

Entity class
```
package data.mongo.data.entity.inventory;

import data.mongo.data.listener.InventoryContentListeners;
import dev.morphia.annotations.*;
import org.bson.types.ObjectId;
import org.bukkit.Bukkit;
import org.bukkit.inventory.Inventory;
import org.bukkit.inventory.ItemStack;

import java.util.*;

@Entity("inventory")
@Indexes({
        @Index(fields = {@Field("uuid"), @Field("key")})
})
@EntityListeners(InventoryContentListeners.class)
public class InventoryContent {

    @Id
    private ObjectId id;

    private UUID uuid;

    private String key;

    private List<Map<String, Object>> serializedContent = new ArrayList<>();

    @Transient
    private List<ItemStack> items = new ArrayList<>();

    public InventoryContent() {
        // Empty constructor required by Morphia
    }

    public InventoryContent(UUID uuid, String key) {
        this.uuid = uuid;
        this.key = key;
    }

    public InventoryContent(UUID uuid, String key, ItemStack... contents) {
        this.uuid = uuid;
        this.key = key;
        this.items = Arrays.asList(contents);
    }

    // region Getters & Setters

    public ObjectId getId() {
        return id;
    }

    public void setId(ObjectId id) {
        this.id = id;
    }

    public UUID getUuid() {
        return uuid;
    }

    public void setUuid(UUID uuid) {
        this.uuid = uuid;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public List<ItemStack> getContents() {
        return items;
    }

    public void setContents(List<ItemStack> itemStacks) {
        this.items = itemStacks;
    }

    public List<Map<String, Object>> getSerializedContent() {
        return serializedContent;
    }

    public void setSerializedContent(List<Map<String, Object>> serializedContent) {
        this.serializedContent = serializedContent;
    }

    // endregion
}
```

Stacktrace
```[19:11:15 WARN]: org.apache.commons.lang.UnhandledException: Plugin Essentials v1.0 generated an exception while executing task 184
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.StackOverflowError
	at dev.morphia.converters.Converters.getEncoder(Converters.java:265)
	at dev.morphia.converters.DefaultConverters.getEncoder(DefaultConverters.java:100)
	at dev.morphia.converters.CustomConverters.getEncoder(CustomConverters.java:55)
	at dev.morphia.converters.Converters.getEncoder(Converters.java:296)
	at dev.morphia.converters.Converters.hasDbObjectConverter(Converters.java:139)
	at dev.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:93)
	at dev.morphia.mapping.Mapper.writeMappedField(Mapper.java:876)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:982)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:593)
	at dev.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98)
	at dev.morphia.mapping.Mapper.writeMappedField(Mapper.java:876)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:982)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:593)
	at dev.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98)
	at dev.morphia.mapping.Mapper.writeMappedField(Mapper.java:876)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:982)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:593)
	at dev.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:98)
	at dev.morphia.mapping.Mapper.writeMappedField(Mapper.java:876)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:982)
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:593)```

**Comment by evanchooly** [comment]
i created a project to try to recreate this and I'm not having much luck.  I created an instance of `InventoryContent` with one `ItemStack` and successfully saved it.  My guess is that the problem is with `serializedContent`.  Chances are you have some circular references in there.  You might try removing the data from that field and see if you get the same problem.

**Comment by evanchooly** [comment]
clearing from 1.5.3 so I can release.  this might end up in a 1.5.4 depending on the resolution.

**Comment by wilmervanheerde** [comment]
Yes, it works with a single ItemStack because I think the issue arises when introducing an Iterable.

I added `serializedContent` as a workaround for the problem, it has nothing to do with the original issue.

**Comment by evanchooly** [comment]
OK.  I'll give it another go tomorrow hopefully.  If I can't recreate it, i'll push my test project to github and perhaps you can show what's different and we can work out a solution.

**Comment by evanchooly** [comment]
I'm digging deeper but can you share your InventoryContentListeners implementation?  I have a feeling the problem is in there somewhere.

**Comment by evanchooly** [comment]
no response for a while so i'm going to consider this as solved elsewhere/gone away.
