### ISSUE TITLE
@Property annotation disrupts aggregation mapping

### ISSUE THREAD

**Issue by mweiczorek** [MorphiaOrg/morphia#1334]
Using 1.4.1

I'm getting this error when trying to aggregate, using a class to specify the aggregation results:
`MappingException: Error setting value from converter (IdentityConverter) for...`

In the handler:

    final Dao<Client> clientDao = new Dao<>(Client.class);
    final Iterator<ClientAggregate> iterator = clientDao.newAggregation()
            .match(query)
            .lookup(DbCollections.PHONE_NUMBERS, Client.PRIMARY_PHONE_ID, Phone.ID, Client.PRIMARY_PHONE)
            .unwind(Client.PRIMARY_PHONE)
            .aggregate(ClientAggregate.class);

ClientAggregate.java

	public class ClientAggregate extends Client {

	    @Property(PRIMARY_PHONE)  // <-- causes failure
	    private Phone primaryPhone;

	}

I'm not sure if this is by design, but I always annotate my fields with PSFS values, so I can make any changes to the values globally instead of refactoring the actual property name.

If I remove the `@Property` annotation and name the field the same as the `as` option during the `$lookup` stage, it works fine. Is there a reason this fails, because it would be nice to use the annotation rather than relying on the actual field name.

**Comment by evanchooly** [comment]
Can you post the full stack trace?

**Comment by mweiczorek** [comment]
First, I've since refactored to account for the fact that the `preserveNullAndEmptyArrays` option is not configurable using `$unwind`, which was causing documents to not show up when a nullable value was encountered. So I've done away with unwinding, and adding all results to a list, then checking if the list
is non-null and has a size greater than 0 before attempting to reference the first object in the list. (See first image). It's pretty much a manual unwinding.

When I add the `@Property` annotation, I get the following exception (only my classes are in the stack):

	java.lang.ClassCastException: com.mongodb.BasicDBObject cannot be cast to com.rippleapis.models.documents.Phone
		at com.rippleapis.models.aggregates.ClientAggregate.getPrimaryPhone(ClientAggregate.java:23)
		at com.rippleapis.databind.ClientAggregatedOutput.compileOutput(ClientAggregatedOutput.java:31)
		at com.rippleapis.databind.ClientAggregatedOutput.compileOutput(ClientAggregatedOutput.java:13)
		at com.rippleapis.mongo.AggregatedOutput.get(AggregatedOutput.java:97)
		at com.rippleapis.rest.handlers.clients.ClientGetter.handle(ClientGetter.java:20)
		at com.rippleapis.rest.handlers.clients.ClientGetter.handle(ClientGetter.java:12)
		at com.rippleapis.handlers.ProvidedIdHandler.handle(ProvidedIdHandler.java:35)

Without the annotation, it works as expected.

So I went back and temporarily reinstated the `$unwind` operation on that one field `primaryPhone`, and when annotated, this exception is thrown:

	dev.morphia.mapping.MappingException: Could not map com.rippleapis.models.aggregates.ClientAggregate with ID: 5ca510fbf79df22edca5013a in database 'ripple'
		at dev.morphia.mapping.Mapper.fromDb(Mapper.java:287)
		at dev.morphia.mapping.Mapper.fromDBObject(Mapper.java:193)
		at dev.morphia.query.MorphiaIterator.convertItem(MorphiaIterator.java:134)
		at dev.morphia.query.MorphiaIterator.processItem(MorphiaIterator.java:146)
		at dev.morphia.query.MorphiaIterator.next(MorphiaIterator.java:117)
		at com.google.common.collect.Iterators.addAll(Iterators.java:367)
		at com.google.common.collect.Lists.newArrayList(Lists.java:163)
		at com.rippleapis.mongo.AggregatedOutput.compileAggregation(AggregatedOutput.java:87)
		at com.rippleapis.mongo.AggregatedOutput.get(AggregatedOutput.java:95)
		at com.rippleapis.rest.handlers.clients.ClientGetter.handle(ClientGetter.java:20)
		at com.rippleapis.rest.handlers.clients.ClientGetter.handle(ClientGetter.java:12)
		at com.rippleapis.handlers.ProvidedIdHandler.handle(ProvidedIdHandler.java:35)
		at io.injest.core.http.HandlerProcessor.processRequest(HandlerProcessor.java:65)
		at io.injest.core.http.HandlerInstance.invoke(HandlerInstance.java:97)
		at io.injest.core.http.Handler.handleRequest(Handler.java:76)
		at io.undertow.server.RoutingHandler.handleRequest(RoutingHandler.java:93)
		at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
		at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:255)
		at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136)
		at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:151)
		at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:92)
		at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:51)
		at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
		at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291)
		at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286)
		at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
		at org.xnio.nio.QueuedNioTcpServer$1.run(QueuedNioTcpServer.java:129)
		at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:582)
		at org.xnio.nio.WorkerThread.run(WorkerThread.java:466)
	Caused by: dev.morphia.mapping.MappingException: Error setting value from converter (IdentityConverter) for com.rippleapis.models.aggregates.ClientAggregate.primaryPhone to { "_id" : { "$oid" : "5ca67df7f79df24fac8988d2"} , "value" : "+442655266556" , "number" : "2655266556" , "countryCode" : "44" , "type" : "MOBILE"}
		at dev.morphia.converters.Converters.fromDBObject(Converters.java:128)
		at dev.morphia.mapping.ValueMapper.fromDBObject(ValueMapper.java:20)
		at dev.morphia.mapping.Mapper.readMappedField(Mapper.java:844)
		at dev.morphia.mapping.Mapper.fromDb(Mapper.java:282)
		... 28 more
	Caused by: java.lang.IllegalArgumentException: Can not set com.rippleapis.models.documents.Phone field com.rippleapis.models.aggregates.ClientAggregate.primaryPhone to com.mongodb.BasicDBObject
		at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
		at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
		at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
		at java.lang.reflect.Field.set(Field.java:764)
		at dev.morphia.mapping.MappedField.setFieldValue(MappedField.java:433)
		at dev.morphia.converters.Converters.fromDBObject(Converters.java:126)
		... 31 more

The value it's attempting to assign is not null and shows properly in the debugger. It only fails if the annotation is present.

![01](https://user-images.githubusercontent.com/224439/55595603-e61a1980-576e-11e9-8ac1-c499a9e3d6ae.png)

It's clear that it's attempting to cast a `BasicDBObject` to my defined `Phone` class. 

![01](https://user-images.githubusercontent.com/224439/55595673-3a24fe00-576f-11e9-9f9f-89edbdb7b363.png)

But when the `@Property` annotation is removed, it shows up in the debugger as `Phone`, and not `BasicDBObject`:

![002](https://user-images.githubusercontent.com/224439/55595814-c6372580-576f-11e9-93b7-43e0a62755a7.png)

**Comment by evanchooly** [comment]
OK.  Thank you for all the detail.  I'll take a look at this but i'm half afraid we're up against limitations in the current mapper that I've refactored/fixed in 2.0 which would mean a proper fix isn't necessarily imminent.  We'll see what some research finds out, though.

**Comment by evanchooly** [comment]
what happens if you use `@Embedded` there?  That's the correct annotation there...

**Comment by mweiczorek** [comment]
`@Embedded` works as expected. Honestly never crossed my mind to use that. I'll show myself out...

**Comment by evanchooly** [comment]
If it's any consolation, I should have noticed that from the start, too.  Glad it's working, though.  I'll close this out now but if you run in to anything else, don't hesitate to file a new issue and I'll take a look.
