### ISSUE TITLE
Morphia MappingException : Unable to query

### ISSUE THREAD

**Issue by Nandinijain24** [MorphiaOrg/morphia#1362]
Upgraded from morphia 1.4 to 1.5.3 and I am facing below issue while querying

**User class** 

```java
@Entity("userModel")
@JsonIgnoreProperties("systemId")
@Indexes({ @Index(fields = { @Field("email") }, options = @IndexOptions(unique = true)),
		@Index(fields = { @Field("name") }, options = @IndexOptions(unique = true)) })
public class UserModel implements Serializable {
  private static final long serialVersionUID = 1L;
    @Id
    private ObjectId systemId;
    @Property("userId")
    private String id;
    private String email;
    private String name;
    //getters setters
}
```
**Below is query to get all users -**

```java	
datasource.createQuery(UserModel.class).find(new FindOptions()).toList();
```	

This is giving "dev.morphia.mapping.MappingException" exception.

```java	
Caused by: dev.morphia.mapping.MappingException: Error setting value from converter (ObjectIdConverter) for com.project.entity.UserModel.systemId to 5d15abaabc4267e0614989a
at dev.morphia.converters.Converters.fromDBObject(Converters.java:129)
at dev.morphia.mapping.ValueMapper.fromDBObject(ValueMapper.java:19)
at dev.morphia.mapping.Mapper.readMappedField(Mapper.java:889)
at dev.morphia.mapping.Mapper.fromDb(Mapper.java:295)
... 98 common frames omitted
Caused by: java.lang.IllegalArgumentException: Can not set org.bson.types.ObjectId field com.project.entity.UserModel.systemId to com.project.entity.UserModel
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(Unknown Source)
at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(Unknown Source)
at sun.reflect.UnsafeObjectFieldAccessorImpl.set(Unknown Source)
at java.lang.reflect.Field.set(Unknown Source)
at dev.morphia.mapping.MappedField.setFieldValue(MappedField.java:454)
at dev.morphia.converters.Converters.fromDBObject(Converters.java:127)
```

Please suggest.

**Comment by evanchooly** [comment]
I used the [reproducer](https://github.com/MorphiaOrg/reproducer) to try to recreate this.  I created a new instance of your entity above and did a save and a fetch and everything worked.  So there appears to be some missing context here that would lead to this error.

**Comment by Nandinijain24** [comment]
Got the issue. It was due to wrong package path in morphia.mapPackage.
