### ISSUE TITLE
Classloader problem while using with Ktor

### ISSUE THREAD

**Issue by kschethan** [MorphiaOrg/morphia#1375]
**Describe the bug**
I have been working on a Ktor project. I found Morphia for my DB needs and I was really impressed by the work you guys have done. Really appreciate it.

However, I found that the classloader which Morphia uses is different from the one Ktor uses, because of this Morphia can never write/read any of the Entities. 

Here is the error thrown by Morphia for this.

`
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can not set org.bson.types.ObjectId field com.morphia.ktest.data.Animal.id to com.morphia.ktest.data.Animal
	at dev.morphia.mapping.ValueMapper.toDBObject(ValueMapper.java:28) ~[core-1.5.3.jar:?]
	at dev.morphia.mapping.Mapper.writeMappedField(Mapper.java:905) ~[core-1.5.3.jar:?]
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:1020) ~[core-1.5.3.jar:?]
	... 56 more
Caused by: java.lang.IllegalArgumentException: Can not set org.bson.types.ObjectId field com.morphia.ktest.data.Animal.id to com.morphia.ktest.data.Animal
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167) ~[?:1.8.0_144]
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171) ~[?:1.8.0_144]
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:58) ~[?:1.8.0_144]
	at sun.reflect.UnsafeObjectFieldAccessorImpl.get(UnsafeObjectFieldAccessorImpl.java:36) ~[?:1.8.0_144]
	at java.lang.reflect.Field.get(Field.java:393) ~[?:1.8.0_144]
	at dev.morphia.mapping.MappedField.getFieldValue(MappedField.java:245) ~[core-1.5.3.jar:?]
	at dev.morphia.converters.Converters.toDBObject(Converters.java:230) ~[core-1.5.3.jar:?]
	at dev.morphia.mapping.ValueMapper.toDBObject(ValueMapper.java:26) ~[core-1.5.3.jar:?]
	at dev.morphia.mapping.Mapper.writeMappedField(Mapper.java:905) ~[core-1.5.3.jar:?]
	at dev.morphia.mapping.Mapper.toDBObject(Mapper.java:1020) ~[core-1.5.3.jar:?]
	... 56 more
`

I am also attaching the screenshot showing the different classloader used by Morphia and Ktor.

I even tried the `MapperOptions.builder()` to provide the classloader via the `defaultCreater` but doesn't seem to affecting anything.

I have a sample project which I am linking here for anybody to verify/check this.
https://github.com/kschethan/ktest-morphia

I'd really appreciate some solutions(if any) or any kind of work around for now(I know you guys are busy with 3.0).

<img width="1406" alt="Screenshot 2019-08-10 at 12 18 14 AM" src="https://user-images.githubusercontent.com/9974824/62801956-793fd300-bb04-11e9-8cb5-78fd1e00d1d8.png">

**Comment by evanchooly** [comment]
Thanks for the kind words and especially the reproducer.  I'll try to track it down.

**Comment by kschethan** [comment]
Hi, 

I was able to work around this for now by making the following change in the application.conf.

`
ktor {
  application {
    modules = [com.morphia.ktest.HelloKt.main]
  }

  deployment {
    port = 8081
    watch = [ com.morphia.ktest ]
  }
  environment = ${?KTOR_ENV}
}
` 

You can refer the latest commit on the repo above for the exact changes.

Thought I will share this if anybody else has the same problem.

**Comment by evanchooly** [comment]
hrm.  I'm not actually sure how to run this one.  I've only poked at ktor and haven't used it in anger yet...

**Comment by kschethan** [comment]
You can run this gradle project by `./gradlew run`.
