### ISSUE TITLE
Guice extension not being utilized for @Embedded objects

### ISSUE THREAD

**Issue by jonahseguin** [MorphiaOrg/morphia#1400]
**Describe the bug**
When an `@Embdedded` object is stored in an entity, it fails to utilize the Guice instantiator when creating the embedded object, instead for some reason it is attempting to instantiate using a normal no-args constructor.
The Guice instantiation/injection works **perfectly** for Entity classes themselves, but doesn't function for embedded objects within the Entity's class.

For example, here is the constructor for my main entity, `Profile.class`
```java
@Inject
    public Profile(ProfileCache<Profile> cache, Core core) {
        super(cache);
        this.core = core;
        this.groups = new ProfileGroupCache(core.getGroupManager());
    }
```
This functions correctly.
However, I have an `@Embedded` field for my `ProfileGroupCache.class` object:
```java
@Embedded("profileGroups") // Groups for this player
    private ProfileGroupCache groups;
```
The `ProfileGroupCache.class` object has the following constructor exclusively:
```java
@Inject
    public ProfileGroupCache(GroupManager groupManager) {
        this.core = Core.getInstance();
        this.groupManager = groupManager;
        this.groups = new HashMap<>();
    }
```

However, when the entity is mapped, I get the following error:
```
 java.lang.RuntimeException: java.lang.RuntimeException: dev.morphia.mapping.MappingException: No usable constructor for org.hcgames.core.permission.groups.profile.ProfileGroupSet
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:84)
[18:55:35 WARN]:        at dev.morphia.mapping.Mapper.readMappedField(Mapper.java:893)
[18:55:35 WARN]:        at dev.morphia.mapping.Mapper.fromDb(Mapper.java:295)
[18:55:35 WARN]:        at dev.morphia.mapping.Mapper.fromDBObject(Mapper.java:202)
[18:55:35 WARN]:        at dev.morphia.query.internal.MorphiaCursor.next(MorphiaCursor.java:87)
[18:55:35 WARN]:        at dev.morphia.query.internal.MorphiaCursor.toList(MorphiaCursor.java:57)
[18:55:35 WARN]:        at com.jonahseguin.payload.mode.profile.store.ProfileStoreMongo.get(ProfileStoreMongo.java:33)
[18:55:35 WARN]:        at com.jonahseguin.payload.mode.profile.PayloadProfileController.load(PayloadProfileController.java:152)
[18:55:35 WARN]:        at com.jonahseguin.payload.mode.profile.PayloadProfileController.cacheNetworkNode(PayloadProfileController.java:199)
[18:55:35 WARN]:        at com.jonahseguin.payload.mode.profile.PayloadProfileController.cache(PayloadProfileController.java:76)
[18:55:35 WARN]:        at com.jonahseguin.payload.mode.profile.listener.ProfileListener.lambda$onProfileCachingStart$0(ProfileListener.java:50)
[18:55:35 WARN]:        at java.util.ArrayList.forEach(Unknown Source)
[18:55:35 WARN]:        at com.jonahseguin.payload.mode.profile.listener.ProfileListener.onProfileCachingStart(ProfileListener.java:45)
[18:55:35 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:55:35 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:55:35 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:55:35 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[18:55:35 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[18:55:35 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[18:55:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[18:55:35 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:482)
[18:55:35 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener$LoginHandler.fireEvents(LoginListener.java:270)
[18:55:35 WARN]:        at net.minecraft.server.v1_12_R1.LoginListener$3.run(LoginListener.java:223)
[18:55:35 WARN]: Caused by: java.lang.RuntimeException: dev.morphia.mapping.MappingException: No usable constructor for org.hcgames.core.permission.groups.profile.ProfileGroupSet
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:84)
[18:55:35 WARN]:        at dev.morphia.mapping.Mapper.readMappedField(Mapper.java:893)
[18:55:35 WARN]:        at dev.morphia.mapping.Mapper.fromDb(Mapper.java:295)
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:73)
[18:55:35 WARN]:        ... 22 more
[18:55:35 WARN]: Caused by: dev.morphia.mapping.MappingException: No usable constructor for org.hcgames.core.permission.groups.profile.ProfileGroupSet
[18:55:35 WARN]:        at dev.morphia.mapping.DefaultCreator.createInstance(DefaultCreator.java:82)
[18:55:35 WARN]:        at dev.morphia.mapping.DefaultCreator.createInstance(DefaultCreator.java:92)
[18:55:35 WARN]:        at dev.morphia.mapping.DefaultCreator.createInstance(DefaultCreator.java:106)
[18:55:35 WARN]:        at dev.morphia.ext.guice.GuiceObjectFactory.createInstance(GuiceObjectFactory.java:92)
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.readMapOrCollectionOrEntity(EmbeddedMapper.java:217)
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.access$000(EmbeddedMapper.java:24)
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper$1.eval(EmbeddedMapper.java:191)
[18:55:35 WARN]:        at dev.morphia.utils.IterHelper.loopMap(IterHelper.java:43)
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.readMap(EmbeddedMapper.java:179)
[18:55:35 WARN]:        at dev.morphia.mapping.EmbeddedMapper.fromDBObject(EmbeddedMapper.java:49)
[18:55:35 WARN]:        ... 25 more
[18:55:35 WARN]: Caused by: dev.morphia.mapping.MappingException: No usable constructor for org.hcgames.core.permission.groups.profile.ProfileGroupSet
[18:55:35 WARN]:        at dev.morphia.mapping.DefaultCreator.getNoArgsConstructor(DefaultCreator.java:54)
[18:55:35 WARN]:        at dev.morphia.mapping.DefaultCreator.createInstance(DefaultCreator.java:73)
[18:55:35 WARN]:        ... 34 more
[18:55:35 WARN]: Caused by: java.lang.NoSuchMethodException: org.hcgames.core.permission.groups.profile.ProfileGroupSet.<init>()
[18:55:35 WARN]:        at java.lang.Class.getConstructor0(Unknown Source)
[18:55:35 WARN]:        at java.lang.Class.getDeclaredConstructor(Unknown Source)
[18:55:35 WARN]:        at dev.morphia.mapping.DefaultCreator.getNoArgsConstructor(DefaultCreator.java:50)
[18:55:35 WARN]:        ... 35 more
```
Despite using the guice extension with my Morphia instance:
```java
new GuiceExtension(morphia, injector);
```

Because of this error stacktrace:
```java
at dev.morphia.ext.guice.GuiceObjectFactory.createInstance(GuiceObjectFactory.java:92)
```

Which is:
See https://github.com/MorphiaOrg/morphia/blob/master/guice-plug/src/main/java/dev/morphia/ext/guice/GuiceObjectFactory.java#L92

the `createInstance` method is calling this piece of code:
```java
return injectMembers(delegate.createInstance(mapper, mf, dbObj));
```

My guess would be this error is being caused by this field within the `ProfileGroupCache.class`
```java
@Embedded
    private Map<String, ProfileGroupSet> groups;
```

My `ProfileGroupSet` object also has an applicable constructor:
```java
@Inject
    public ProfileGroupSet(GroupManager groupManager) {
        this.core = Core.getInstance();
        this.groupManager = groupManager;
        this.groups = new HashSet<>();
    }
```

This whole error is confusing me.

All of my objects have an applicable constructor with an `@Inject` annotation

** Please complete the following information: **
 - Server Version: latest
 - Driver Version: latest
 - Morphia Version: latest (1.5.8)

**Comment by evanchooly** [comment]
I'm trying to recreate this bug and not having much luck.  Can you use the [reproducer](https://github.com/MorphiaOrg/reproducer) to create a small test case I can poke at?  I'll keep trying here, too.

**Comment by jonahseguin** [comment]
Apologies for the delay.  Will use the reproducer to try and make it happen.

**Comment by jonahseguin** [comment]
My simple workaround for the time being was just leaving an empty/default constructor available in all of my `@Embedded` entities.

**Comment by evanchooly** [comment]
Is this still an active concern?  If not, I'll close it so I can push a 1.6.0.
