### ISSUE TITLE
ClassCastException when retrieving entities with date-time fields and a load lifecycle listener

### ISSUE THREAD

**Issue by justinrstout** [MorphiaOrg/morphia#1430]
**Describe the bug**
If an `@Entity` has a non-null date-time-type field such as `Instant`, `LocalDateTime`, or `Date`, as well as a lifecycle listener method annotated with either `@PreLoad` or `@PostLoad`, Morphia throws `java.lang.ClassCastException: class java.util.Date cannot be cast to class java.lang.Long` when I try to `.find()` a saved entity. Full stacktrace included in "Additional Context" section.

**To Reproduce**
Given an entity like this:
```
@Entity
public class TimeEntity {
    @Id
    public ObjectId id;
    public Instant myInstant;

    @PreLoad
    public void preload() {
    }
}
```

When I execute this test:
```
    @Test
    public void testGet() {
        final Datastore datastore = // initialize mongo connection and datastore
        final TimeEntity entity = new TimeEntity();
        entity.myInstant = Instant.now();
        final TimeEntity save = datastore.save(entity);
        final TimeEntity find = datastore.find(TimeEntity.class).field("_id").equal(save.id).first();
    }
```

The exception is thrown. If I remove the `@PreLoad` annotation from the entity's method, no exception is thrown and the `find` variable is correctly instantiated.

**Expected behavior**
No exception is thrown and the entity is populated with the correct date/time value.

** Please complete the following information: **
 - Server Version: 4.0.12
 - Driver Version: 3.11.1
 - Morphia Version: 2.0.0-ALPHA2

**Additional context**
```
class java.util.Date cannot be cast to class java.lang.Long (java.util.Date and java.lang.Long are in module java.base of loader 'bootstrap')
java.lang.ClassCastException: class java.util.Date cannot be cast to class java.lang.Long (java.util.Date and java.lang.Long are in module java.base of loader 'bootstrap')
	at dev.morphia.mapping.codec.reader.DocumentReader.readDateTime(DocumentReader.java:91)
	at org.bson.codecs.jsr310.DateTimeBasedCodec.validateAndReadDateTime(DateTimeBasedCodec.java:34)
	at org.bson.codecs.jsr310.LocalDateTimeCodec.decode(LocalDateTimeCodec.java:46)
	at org.bson.codecs.jsr310.LocalDateTimeCodec.decode(LocalDateTimeCodec.java:42)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:93)
	at dev.morphia.mapping.codec.BaseMorphiaCodec.decodePropertyModel(BaseMorphiaCodec.java:148)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decodePropertyModel(MorphiaCodec.java:160)
	at org.bson.codecs.pojo.PojoCodecImpl.decodeProperties(PojoCodecImpl.java:197)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:181)
	at com.mongodb.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.codecs.configuration.LazyCodec.decode(LazyCodec.java:47)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:413)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:309)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:259)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:450)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:72)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:218)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:269)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:131)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:123)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
	at com.mongodb.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
	at com.mongodb.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:731)
	at com.mongodb.operation.FindOperation$1.call(FindOperation.java:725)
	at com.mongodb.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:463)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:725)
	at com.mongodb.operation.FindOperation.execute(FindOperation.java:89)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:189)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:143)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at dev.morphia.query.QueryImpl.prepareCursor(QueryImpl.java:543)
	at dev.morphia.query.QueryImpl.execute(QueryImpl.java:227)
	at dev.morphia.query.QueryImpl.first(QueryImpl.java:237)
	at dev.morphia.query.QueryImpl.first(QueryImpl.java:232)
	at com.mytest.TimeTest.testGet
```

**Comment by evanchooly** [comment]
*sigh*  i know exactly what that problem is.  :)  I'll see what I can do.  Thanks.

**Comment by evanchooly** [comment]
Can you try again with `-SNAPSHOT`?  I think i have that fixed.  I have a few other changes I want to make before pushing a `BETA2` but I think the snapshot will get you fixed.

**Comment by justinrstout** [comment]
Yep, no error with the current SNAPSHOT

**Comment by evanchooly** [comment]
Fantastic.  I just pushed the BETA2 release.  It's syncing to maven central now.
