### ISSUE TITLE
Aggregation broken in 2.0.0-BETA2

### ISSUE THREAD

**Issue by richarddd** [MorphiaOrg/morphia#1447]
**Describe the bug**
The reference codec tries to resolve fields in Entity when using the aggregation.

**To Reproduce**
1. Create an entity class with a  `@Reference(idOnly = true)` annotation
2. Perform an aggregation (with lookup) on that class
3. See error

**Expected behavior**
Get the results without the internal fetch for references

** Please complete the following information: **
 - Server Version: 4.2
 - Driver Version: 
 - Morphia Version: 2.0.0-BETA2

**Additional context**
Currently, there is no way to tell morphia to skip fetching the referenced resource. In versions prior to 2.0, we could set `idOnly = true` and morphia would not try to fetch the reference automatically (but still map to the correct class).

It would be great if we could have something like `@Reference(fetch = false)` to be able to use the aggregation pipeline again.

**Comment by evanchooly** [comment]
can you share the pipeline you're trying to use and I'll take a look at it after I wrap up my current issue.  Thanks.

**Comment by richarddd** [comment]
Here is an example:

```kotlin
abstract class BaseEntity(
    @Id
    val id: ObjectId? = null
)

@Entity
data class Inventory(
    val sku: String = "",
    val description: String = "",
    val stockCount: Int = 0
) : BaseEntity()

@Entity
data class Order(
    @Reference(idOnly = true)
    val item: Inventory? = null,
    val price: Int = 0,
    val quantity: Int = 0
) : BaseEntity()
```
```kotlin
fun main() {


    val datastore = Morphia.createDatastore(MongoClients.create(), "demo")
    datastore.mapper.mapPackage("se.davison.morphia2.enteries")
    datastore.ensureIndexes()


    val items = datastore.save(
        listOf(
            Inventory("apple", "Apple", 1),
            Inventory("banana", "Banana", 5),
            Inventory("kiwi", "Kiwi", 10)
        )
    )

    val savedOrders = datastore.save(
        listOf(
            Order(items[0], 10, 1),
            Order(items[1], 20, 5),
            Order(items[2], 20, 10)
        )
    )

    val orders = datastore.aggregate(Order::class.java)
        .lookup(Lookup.from(Inventory::class.java).`as`("item").foreignField("_id").localField("item"))
        .unwind(Unwind.on("item"))
        .execute(Order::class.java).toList()


    println("order size: ${orders.size}")
}
```
Stack:
```
Exception in thread "main" dev.morphia.mapping.lazy.proxy.ReferenceException: Referenced 'Inventory' entity could not be found during a fetch.
	at dev.morphia.mapping.experimental.SingleReference.get(SingleReference.java:77)
	at dev.morphia.mapping.codec.references.ReferenceCodec.fetch(ReferenceCodec.java:208)
	at dev.morphia.mapping.codec.references.ReferenceCodec.decode(ReferenceCodec.java:151)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:66)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:88)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:43)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:70)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:48)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:70)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:412)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:308)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:500)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:224)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
	at com.mongodb.internal.operation.CommandOperationHelper$5.call(CommandOperationHelper.java:206)
	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:462)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:203)
	at com.mongodb.internal.operation.AggregateOperationImpl.execute(AggregateOperationImpl.java:189)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:296)
	at com.mongodb.internal.operation.AggregateOperation.execute(AggregateOperation.java:41)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at dev.morphia.aggregation.experimental.AggregationImpl.execute(AggregationImpl.java:105)
	at se.davison.morphia2.MainKt.main(Main.kt:66)
	at se.davison.morphia2.MainKt.main(Main.kt)

Process finished with exit code 1
```

**Comment by evanchooly** [comment]
Excellent.  Thank you.  I've figured out what it is.  With that `$lookup`, the remote document is already there so the codecs decode directly in to the entity type rather than the ID type.  Curiously, most of the code to handle this case is already in morphia:  the documents are correctly decoded in to the entity types.  It's just the bookkeeping in the reference code isn't catching all that and is trying to fetch again.  I have your case fixed locally.  I need to update the tests to check this use case for list/map/set references and I think that'll cover it.  Once that is done, a -SNAPSHOT build will be automatically pushed if you want to try using that.  If not, I think i'm going to go with a -BETA3 now that I've reworked the update code elsewhere and this fix would go in to that.

Thanks for the reproducer and thanks for trying the betas.  I think we're getting close to "done."

**Comment by richarddd** [comment]
> Excellent. Thank you. I've figured out what it is. With that `$lookup`, the remote document is already there so the codecs decode directly in to the entity type rather than the ID type. Curiously, most of the code to handle this case is already in morphia: the documents are correctly decoded in to the entity types. It's just the bookkeeping in the reference code isn't catching all that and is trying to fetch again. I have your case fixed locally. I need to update the tests to check this use case for list/map/set references and I think that'll cover it. Once that is done, a -SNAPSHOT build will be automatically pushed if you want to try using that. If not, I think i'm going to go with a -BETA3 now that I've reworked the update code elsewhere and this fix would go in to that.
> 
> Thanks for the reproducer and thanks for trying the betas. I think we're getting close to "done."

Thanks! Great work (as always)!!! 🙌
