### ISSUE TITLE
back to 2.0.1 .. zippo joy.. "Classnot found".. on a bone-simple fetch , yes package is mapped and its not a Morphia used field called 'ClassName'.. etc.

### ISSUE THREAD

**Issue by johnda98** [MorphiaOrg/morphia#1501]
like pulling teeth .. package is mapped.. etc.. followed Docs and STILL no joy

Looks like morphia not finding my defined class despite the package being mapped..  stack is 

```
"Caused by: java.lang.NoClassDefFoundError: java/lang/instrument/ClassFileTransformer
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default$WrappingDispatcher.load(ClassLoadingStrategy.java:357)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$Default.load(ClassLoadingStrategy.java:143)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:100)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:5686)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.references.ReferenceCodec.createProxy(ReferenceCodec.java:232)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.references.ReferenceCodec.fetch(ReferenceCodec.java:259)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.references.ReferenceCodec.decode(ReferenceCodec.java:151)
	at org.mongodb.bson@4.0.5/org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:66)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:88)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:43)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:70)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:48)
	at morphia.core@2.0.1/dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:70)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.mongodb.bson@4.0.5/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.mongodb.bson@4.0.5/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.mongodb.bson@4.0.5/org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
	at org.mongodb.bson@4.0.5/org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.mongodb.bson@4.0.5/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.mongodb.bson@4.0.5/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:412)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:308)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:500)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:224)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:631)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:625)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:462)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:625)
	at org.mongodb.driver.core@4.0.5/com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:77)
	at org.mongodb.driver.sync.client@4.0.5/com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190)
	at org.mongodb.driver.sync.client@4.0.5/com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at org.mongodb.driver.sync.client@4.0.5/com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at morphia.core@2.0.1/dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:335)
	at morphia.core@2.0.1/dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:202)
	at morphia.core@2.0.1/dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:185)
	at morphia.core@2.0.1/dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:180)
	at org.crob/org.crob.SecondaryController.runquery(SecondaryController.java:54)
	... 58 more
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.ClassFileTransformer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 108 more"
```

code is

tripping obviously on the .first()

```java
        long count  = queryofdataholon.count();
        System.out.println("Data holon count: " + count);

        // System.out.println(" query out " + queryofdataholon.first().toString());

        DataHolon result = queryofdataholon.first();

       System.out.println("singleton" + result.toString());

      //  Query<DataHolonTypeProperty> typeprop = datastore.find(DataHolonTypeProperty.class);
      //  System.out.println(" type " +typeprop.first().toString());



/*
```

more details below...

the prob..

```
	... 58 more
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.ClassFileTransformer
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 108 more
```

pom..

```xml
   </dependency> -->

        <dependency>
            <groupId>dev.morphia.morphia</groupId>
            <artifactId>morphia-core</artifactId>
            <version>2.0.1</version>
        </dependency>
<!--
        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>bson</artifactId>
            <version>4.1.0</version>
        </dependency>-->

        <dependency>
            <groupId>org.mongodb</groupId>
            <artifactId>mongo-java-driver</artifactId>
            <version>3.12.7</version>
        </dependency>
```

entity

```java
package org.crob;

import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Id;
import dev.morphia.annotations.Reference;
import org.bson.types.ObjectId;
import java.util.ArrayList;
import java.util.List;

@Entity("dataholons")
public class DataHolon {
        @Id
        private ObjectId id;
        private String name;
        private String description;


        @Reference(lazy = true)
        private List<DataHolonType>  isaclassificationOf = new ArrayList<>();

        @Reference(lazy = true)
        private List<Interface>  interactsWith = new ArrayList<>();

        @Reference(lazy = true)
        private  List<DataHolonProperty> consistsOf = new ArrayList<>();


        DataHolon() { }

        DataHolon(String name, String description){
            this.name = name;
            this.description = description;
        }


        public ObjectId getId() {
            return id;
        }

        public String getName(){
            return name;
        }

        public String getDescription(){
            return description;
        }

        // get Data holontype

        public List<DataHolonType> getIsclassificationOf() {
            return isaclassificationOf;
        }

        // get uses interfaces(apis)

        public List<Interface> getInteractsWith() {return  interactsWith; }

        // get data holon properties

        public List<DataHolonProperty> getConsistsOf() {return  consistsOf; }



        // Setters

        public void setName(String name){
            this.name = name;
        }

        public void setDescription(String description){
            this.description = description;
        }

        public void setIsclassificationOf(List<DataHolonType> isaclassificationOf) {
            this.isaclassificationOf = isaclassificationOf;
        }

        public void setInteractsWith(List<Interface> interactsWith) {
            this.interactsWith = interactsWith;
       }

        public void setConsistsOf(List<DataHolonProperty> consistsOf) {
            this.consistsOf = consistsOf;
        }


        // toString

        @Override
        public String toString() {
            return "DataHolon [id=" + id + ", name=" + name + ", description=" + description + "]";
        }


    }

 Query<DataHolon> queryofdataholon = datastore.find("dataholons");
      // queryofdataholon.filter(Filters.eq("name", "Casino Industry SW USA"));

        long count  = queryofdataholon.count();
        System.out.println("Data holon count: " + count);

        System.out.println(" query out " + queryofdataholon.first().toString());
```

code

and yes Atlas is all happy and pre-populated with reference objects see image attached

and.. connected ok to Atlas and database all happy..

```java
    public Datastore getDatastore() {

        if (dataStore == null) {

            String dbName = "modsimv1";
            System.out.println("Starting DataStore on DB: " + dbName);

            // same for local or atlas as getMongo already called by inti
            // for Morphia 1.4

            // morphia = new Morphia();
            // morphia.mapPackage("org.crob");
            // dataStore = morphia.createDatastore(mongo,"modsimv1");

            // for Morphia 2.0
            dataStore = Morphia.createDatastore(mongo,"modsimv1");
            dataStore.getMapper().mapPackage("org.crob");


            dataStore.ensureIndexes();
        }

        return dataStore;
    }
```
![Screenshot from 2020-10-01 08-46-16](https://user-images.githubusercontent.com/13384285/94817410-9697c680-03c2-11eb-8b2c-ed9d729ab475.png)

**Comment by evanchooly** [comment]
I'm guessing you're on at least Java 11 but are you using the modulepath or the traditional classpath?  Not being able to find a JDK class is ... odd.

**Comment by johnda98** [comment]
module path and intellij tells me it has all that it needs.. can send you a
copy if you like


*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by johnda98** [comment]
good point  do i have to put my Entity Classes in the module info file ?

*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by johnda98** [comment]
yes java 11 and also using javafx11

*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by johnda98** [comment]
may have a breakthrough here !  after trial and error pinning things down
.. creating collections relationships anyway

ClassnotFoiund on query is the next hurdle

module file is module org.crob {

    requires javafx.controls;
    requires javafx.fxml;
    requires morphia.core;
    requires org.mongodb.driver.sync.client;
    requires org.mongodb.bson;
    requires org.mongodb.driver.core;
    opens org.crob to javafx.fxml, morphia.core, org.mongodb.driver.core;
    exports org.crob;
}


*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by johnda98** [comment]
author1.getList().add(book1);


where author and book objects are fine and dandy and NOT null , I just
added them

*so I have to set the whole list ? with setList<List<Book>) ?   EVERY
time I want to add a new book ??*



*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.

**Comment by johnda98** [comment]
// save the relation.. set the auth for all books

  book1.setAuthor(author1);
  datastore.save(book1);
  book2.setAuthor(author1);
  datastore.save(book2);
  //  AND have to fill the list up in author !

  List<Book> booksforthisauth = Arrays.asList(book1, book2);
  author1.setList(booksforthisauth);

  // the below DOES NOT work.. null pointer  BTW cant understand why
I'm calling a getter to set ??
  // as per elmer.getDirectReports().add(daffy); !!
  // so this line below is junk.. i can only add a full list to add a
new single book ??
  author1.getList().add(book1);

//  author1.getList().add(book2) returns null pointer.. error in morphia code

  datastore.save(author1);


*John D Allen.*


*T +1 417 849 0705 ** CST  | john.allen@leveridgesystems.com
<john.allen@leveridgesystems.com>  | https://www.leveridgesystems.com
<https://www.leveridgesystems.com> | linkedin.com/in/johndallen1
<http://linkedin.com/in/johndallen1> | skype john.allen_67
https://www.yourhashgraphtoken.com <https://www.yourhashgraphtoken.com>*


 Leveridge Systems INC. Reg Missouri Charter #01082460.  The information
contained in this email and any attached files is confidential and intended
solely for the addressee(s). The email may be legally privileged or
prohibited from disclosure and unauthorized use. If you are not the
named addressee you may not use, copy, or disclose this information to any
other person. If you received this message in error please notify the
sender immediately and permanently delete it from your system.
