### ISSUE TITLE
Update from 1.5.8 to 1.6.1 - UUID problem

### ISSUE THREAD

**Issue by Peter0x48** [MorphiaOrg/morphia#1534]
Hi,

I'm updating a project from 1.5.8 (MongoDB Java Driver 3.10.1) to 1.6.1 (bson, driver-core, driver-legacy, driver-sync 4.1.1).

I now have a problem using UUID variables in my entities:
`org.bson.codecs.configuration.CodecConfigurationException: The uuidRepresentation has not been specified, so the UUID cannot be encoded.`
Then I defined the UuidCodec in the codecRegistry of the client builder:
```
CodecRegistry codecRegistry = CodecRegistries.fromRegistries(CodecRegistries.fromCodecs(new UuidCodec(UuidRepresentation.STANDARD)), MongoClient.getDefaultCodecRegistry());
mongoClientOptionsBuilder.codecRegistry(codecRegistry);
```
After that saving of new entities works again. The UUID is then saved as a "UUID" in the database:
`UUID("f3a309a3-fd93-416c-82c3-86353d1fbed2")`

However, loading of the entity does now not work anymore:
```
Exception in thread "main" dev.morphia.mapping.MappingException: Could not map morphia.test.entities.TestEntity with ID: id01 in database 'testDB'
	at dev.morphia.mapping.Mapper.fromDb(Mapper.java:313)
	at dev.morphia.mapping.Mapper.fromDBObject(Mapper.java:215)
	at dev.morphia.query.internal.MorphiaCursor.next(MorphiaCursor.java:87)
	at dev.morphia.query.internal.MorphiaCursor.tryNext(MorphiaCursor.java:93)
	at dev.morphia.query.QueryImpl.first(QueryImpl.java:232)
	at morphia.test.Test.test2(Test.java:47)
	at morphia.test.Test.main(Test.java:37)
Caused by: dev.morphia.mapping.MappingException: Error setting value from converter (IdentityConverter) for morphia.test.entities.TestEntity.dataID to org.bson.types.Binary@1a54f99a
	at dev.morphia.converters.Converters.fromDBObject(Converters.java:131)
	at dev.morphia.mapping.ValueMapper.fromDBObject(ValueMapper.java:19)
	at dev.morphia.mapping.Mapper.readMappedField(Mapper.java:906)
	at dev.morphia.mapping.Mapper.fromDb(Mapper.java:308)
	... 6 more
Caused by: java.lang.IllegalArgumentException: Can not set final java.util.UUID field morphia.test.entities.TestEntity.dataID to org.bson.types.Binary
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
	at java.lang.reflect.Field.set(Field.java:764)
	at dev.morphia.mapping.MappedField.setFieldValue(MappedField.java:454)
	at dev.morphia.converters.Converters.fromDBObject(Converters.java:129)
	... 9 more
```

If I set the UuidRepresentation to JAVA_LEGACY, the UUID is stored as BinData (which is the same format as in the old Morphia version and loading works again):
`BinData(3, "bEGT/aMJo/PSvh89NYbDgg==")`

Do you know about this problem? What is the preferred solution? Should I use JAVA_LEGACY?

Thank you!

Regards,
Peter

This is my test code to keep this report simple:
Test.java:
```
public class Test {
    public static void main(String[] args) {
        List<ServerAddress> servers = Collections.singletonList(new ServerAddress("127.0.0.1", 27017));

        MongoClientOptions.Builder mongoClientOptionsBuilder = MongoClientOptions.builder();

        CodecRegistry codecRegistry = CodecRegistries.fromRegistries(CodecRegistries.fromCodecs(new UuidCodec(UuidRepresentation.STANDARD)), MongoClient.getDefaultCodecRegistry());
        mongoClientOptionsBuilder.codecRegistry(codecRegistry);

        MongoClientOptions mongoClientOptions = mongoClientOptionsBuilder.build();

        MongoClient mongoClient = new MongoClient(servers, mongoClientOptions);

        Morphia morphia = new Morphia();
        morphia.mapPackage("morphia.test.entities");

        Datastore testDB = morphia.createDatastore(mongoClient, "testDB");

        test1(testDB);
    }

    private static void test1(Datastore datastore) {
        TestEntity testEntity = new TestEntity("id01", UUID.fromString("f3a309a3-fd93-416c-82c3-86353d1fbed2"));

        datastore.save(testEntity);
    }

    private static void test2(Datastore datastore) {
        TestEntity first = datastore.find(TestEntity.class).first();
    }
}
```

TestEntity.java
```
@Entity(value = "testData", noClassnameStored = true)
public class TestEntity {
    @Id
    private final String id;

    private final UUID dataID;

    public TestEntity(String id, UUID dataID) {
        this.id = id;
        this.dataID = dataID;
    }

    public TestEntity() {
        this(null, null);
    }
}
```

 - Server Version: 4.4.2
 - Driver Version: 4.1.1 (from morphia)
 - Morphia Version: 1.6.1

**Comment by evanchooly** [comment]
Try adding the following line to your config:

```java
mapper.getConverters().addConverters(UUIDConverter.class);
```

I think that's the correct syntax.  I'm having to do it a bit from memory.
