### ISSUE TITLE
Update pull does nothing

### ISSUE THREAD

**Issue by gustavomcarmo** [MorphiaOrg/morphia#1537]
Please if anyone can tell me what I'm doing wrong in [this code](https://github.com/esign-consulting/logistics/blob/c0e303137def472ef747d8a8c7c6c620857f5861/logistics-ejb/src/main/java/br/com/esign/logistics/dao/impl/RoutesMapDAOImpl.java#L105), since it doesn't have the expected behavior so far.

```java
    public void removeRouteFromMap(String name, Route route) {
        datastore.find(RoutesMap.class)
            .filter(Filters.eq("name", name))
            .update(UpdateOperators.pull("routes", Filters.eq("name", route.getName())))
            .execute();
    }
```

Thanks!

**Comment by evanchooly** [comment]
It looks fine to me too.  Can you put together a reproducer and I'll take a look?

**Comment by gustavomcarmo** [comment]
I've just tried with another field (slug), as you can see [here](https://github.com/esign-consulting/logistics/blob/b34008131c59406ba1ffb01335c30448d3397de1/logistics-ejb/src/main/java/br/com/esign/logistics/dao/impl/RoutesMapDAOImpl.java#L105), and the exception below was thrown:

```
Caused by: com.mongodb.MongoWriteException: Cannot apply $pull to a non-array value
        at deployment.logistics-ear-1.0-SNAPSHOT.ear//com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1015)
        at deployment.logistics-ear-1.0-SNAPSHOT.ear//com.mongodb.client.internal.MongoCollectionImpl.executeUpdate(MongoCollectionImpl.java:992)
        at deployment.logistics-ear-1.0-SNAPSHOT.ear//com.mongodb.client.internal.MongoCollectionImpl.updateOne(MongoCollectionImpl.java:577)
        at deployment.logistics-ear-1.0-SNAPSHOT.ear//dev.morphia.query.Update.execute(Update.java:55)
        at deployment.logistics-ear-1.0-SNAPSHOT.ear//dev.morphia.query.Update.execute(Update.java:35)
        at deployment.logistics-ear-1.0-SNAPSHOT.ear.br.com.esign-logistics-ejb-1.0-SNAPSHOT.jar//br.com.esign.logistics.dao.impl.RoutesMapDAOImpl.removeRouteFromMap(RoutesMapDAOImpl.java:109)
        at deployment.logistics-ear-1.0-SNAPSHOT.ear.br.com.esign-logistics-ejb-1.0-SNAPSHOT.jar//br.com.esign.logistics.dao.impl.RoutesMapDAOImplAdapter.removeRouteFromMap(RoutesMapDAOImplAdapter.java:94)
```

The document JSON is as following:

```json
{
    "_id": "Test",
    "slug": "test",
    "places": [
        {
            "name": "A"
        },
        {
            "name": "B"
        }
    ],
    "routes": [
        {
            "name": "A -> B",
            "origin": {
                "name": "A"
            },
            "destination": {
                "name": "B"
            },
            "distance": 10,
            "slug": "a-b"
        },
        {
            "name": "B -> A",
            "origin": {
                "name": "B"
            },
            "destination": {
                "name": "A"
            },
            "distance": 10,
            "slug": "b-a"
        }
    ]
}
```

It really makes no sense to me 😞
