### ISSUE TITLE
Cannot load enum declared as an interface [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#155]
This is [Issue 155](http://code.google.com/p/morphia/issues/detail?id=155) moved from a Google Code project.
Added by 2010-11-05T16:00:39.000Z by [joseph.p...@gmail.com](http://code.google.com/u/108658104283195504746/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Low, Milestone-Icebox
### Original description

<b>What version are you using? (Morphia/Driver/MongoDB)</b>
latest snapshot/driver 2.3/mongo 1.7.1

<b>Please include a stack trace below:</b>

```
com.google.code.morphia.mapping.MappingException: Error mapping field:com.google.code.morphia.converters.EnumBehindAnInterfaceTest$ContainerEntity.foo
    at com.google.code.morphia.mapping.Mapper.toDBObject(Mapper.java:355)
    at com.google.code.morphia.DatastoreImpl.entityToDBObj(DatastoreImpl.java:663)
    at com.google.code.morphia.DatastoreImpl.save(DatastoreImpl.java:706)
    at com.google.code.morphia.DatastoreImpl.save(DatastoreImpl.java:786)
    at com.google.code.morphia.DatastoreImpl.save(DatastoreImpl.java:780)
    at com.google.code.morphia.converters.EnumBehindAnInterfaceTest.testEnumBehindAnInterfacePersistence(EnumBehindAnInterfaceTest.java:33)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:28)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:31)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:76)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:193)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:52)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:191)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:42)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:184)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:236)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
Caused by: com.google.code.morphia.mapping.MappingException: com.google.code.morphia.converters.EnumBehindAnInterfaceTest$EnumBehindAnInterface cannot be used; It does not have a no-args constructor.
    at com.google.code.morphia.mapping.MappedClass.discover(MappedClass.java:118)
    at com.google.code.morphia.mapping.MappedClass.<init>(MappedClass.java:102)
    at com.google.code.morphia.mapping.Mapper.getMappedClass(Mapper.java:177)
    at com.google.code.morphia.mapping.Mapper.toDBObject(Mapper.java:345)
    at com.google.code.morphia.mapping.EmbeddedMapper.toDBObject(EmbeddedMapper.java:40)
    at com.google.code.morphia.mapping.Mapper.writeMappedField(Mapper.java:443)
    at com.google.code.morphia.mapping.Mapper.toDBObject(Mapper.java:353)
    ... 29 more
Caused by: java.lang.NoSuchMethodException: com.google.code.morphia.converters.EnumBehindAnInterfaceTest$EnumBehindAnInterface.<init>()
    at java.lang.Class.getConstructor0(Class.java:2706)
    at java.lang.Class.getDeclaredConstructor(Class.java:1985)
    at com.google.code.morphia.mapping.MappedClass.discover(MappedClass.java:115)
    ... 35 more
```

**Comment by evanchooly** [comment]
This bug is 6 years old and no one else has complained.  If someone else hits the same problem, we can reconsider it.  But I'm going to duck this one for now.
