### ISSUE TITLE
Null value handling is broken with lifecycle events

### ISSUE THREAD

**Issue by chenchenyangll** [MorphiaOrg/morphia#1568]
Consider the following scenario, 
```
book
{
    "_id": ObjectId(xxx),
    "id": 1    // human readable id using somewhere else
}

@Entity("book")
public class Book {
    @Id
    ObjectId id;
}
```

In v2.1.4, it will raise:
Exception in thread "main" dev.morphia.mapping.MappingException: Can not set org.bson.types.ObjectId field Book.id to java.lang.Integer

but back in older v1.5.4, it works fine.

**Comment by evanchooly** [comment]
What's happening here is that when reading the document from the database, it's finding a value with the key "id."  It then looks for a mapping with that name or a field with that name.  it finds the `@Id` field and then tries to set the deserialized `Integer` to the `ObjectId` field which, of course, fails.  This likely worked in 1.5.4 (it's been a *long* time so I'm trying to recreate this from memory) because back then, deserialization was driven by the field names in the Java class where 2.x is driven by what keys it finds in the document.  It's done this way because the data coming from the database is essentially a stream and randomly accessing a document like that is far less efficient.

Ulitmately, though, I think this is a mapping bug in your code that you got lucky with in 1.5 but is no longer workable in 2.x.

**Comment by chenchenyangll** [comment]
> What's happening here is that when reading the document from the database, it's finding a value with the key "id." It then looks for a mapping with that name or a field with that name. it finds the `@Id` field and then tries to set the deserialized `Integer` to the `ObjectId` field which, of course, fails. This likely worked in 1.5.4 (it's been a _long_ time so I'm trying to recreate this from memory) because back then, deserialization was driven by the field names in the Java class where 2.x is driven by what keys it finds in the document. It's done this way because the data coming from the database is essentially a stream and randomly accessing a document like that is far less efficient.
> 
> Ulitmately, though, I think this is a mapping bug in your code that you got lucky with in 1.5 but is no longer workable in 2.x.

ok, just changing the name of `@Id` field to `oid` that avoids the unmapped fields' name works.

I've found out another case in which my code works no more (but is good in 1.5)

```
in collection book, we have these kinds of documents
{"name": "BookA"},
{"name": "BookB", "type": 0},
{"name": "BookC", "type": 1},
{"name": "BookD", "type": null}
```

back in 1.5, the following code is fine

```
@Entity("book")
public class Book {
    @Id
    ObjectId id;

    String name;

    int type;
}
```

but in 2.x, `null` value of field `type` in BookD document will cause a NPE (set int to null value). of course, I can accept this though. Change to the following:

```
@Entity("book")
public class Book {
    @Id
    ObjectId id;

    String name;

    Integer type;
}
```

now, it works in 2.x. But what if I need some LifeCycle method to handle the `null` value or do something else

```
@Entity("book")
public class Book {
    @Id
    ObjectId id;

    String name;

    Integer type;

    @PostLoad
    private void foo() {
        // type = (type == null ? 233 : type);
        // or do something else
        // doSomething(name);
    }
}
```

then will lead to a NPE. traceback is like

```
java.lang.NullPointerException: Cannot invoke "org.bson.BsonType.ordinal()" because "bsonType" is null
        at org.bson.codecs.NumberCodecHelper.decodeDouble(NumberCodecHelper.java:97)
        at org.bson.codecs.DoubleCodec.decode(DoubleCodec.java:37)
        at org.bson.codecs.DoubleCodec.decode(DoubleCodec.java:29)
        at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:65)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:87)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeWithLifecycle(EntityDecoder.java:131)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:37)
        at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
        at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
        at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
        at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
        at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
        at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
        at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:412)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:308)
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258)
        at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
        at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:500)
        at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
        at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:224)
        at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110)
        at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
        at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
        at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
        at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:631)
        at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:625)
        at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:462)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:625)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:77)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
        at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:320)
        at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:201)
        at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:196)
```

**Comment by evanchooly** [comment]
Can you put together a [reproducer](https://github.com/MorphiaOrg/reproducer) for this last bit for me to dig in to?

**Comment by chenchenyangll** [comment]
> Can you put together a [reproducer](https://github.com/MorphiaOrg/reproducer) for this last bit for me to dig in to?

see [here](https://github.com/chenchenyangll/reproducer)

**Comment by evanchooly** [comment]
i'll push a release tomorrow
