### ISSUE TITLE
Wildcard generics can cause crashes in certain scenarios

### ISSUE THREAD

**Issue by earomc** [MorphiaOrg/morphia#1571]
**Describe the bug**
A single static field causes an error when calling the getMapper().map(City.class method)

It has something to do with this specific constellation:
private static final Class<? extends FoundingProcedure<City>> PROCEDURE_CLASS = CityFoundingProcedure.class;
Any other static class field doesnt cause the error. Some more narrowing down is needed.

java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at dev.morphia.mapping.codec.pojo.TypeData.getNestedTypeData(TypeData.java:96)
	at dev.morphia.mapping.codec.pojo.TypeData.newInstance(TypeData.java:80)
	at dev.morphia.mapping.codec.pojo.TypeData.newInstance(TypeData.java:64)
	at dev.morphia.mapping.codec.pojo.EntityModelBuilder.processFields(EntityModelBuilder.java:351)
	at dev.morphia.mapping.codec.pojo.EntityModelBuilder.<init>(EntityModelBuilder.java:82)
	at dev.morphia.mapping.Mapper.createEntityModel(Mapper.java:499)
	at dev.morphia.mapping.Mapper.getEntityModel(Mapper.java:126)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.AbstractList$RandomAccessSpliterator.forEachRemaining(AbstractList.java:720)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at dev.morphia.mapping.Mapper.map(Mapper.java:302)
	at dev.morphia.mapping.Mapper.map(Mapper.java:139)
	at com.foo.ReproducerTest.reproduce(ReproducerTest.java:42)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**To Reproduce**
I made a morphia reproducer which shows the issue:
https://github.com/earomc/reproducer

**Expected behavior**
The field should be ignored as it is static and there shouldn't be any errors.

** Please complete the following information: **
 - Server Version: 4.4
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.4

**Additional context**
I added the reproducer as a zip as well. Just in case ...
[reproducer-master.zip](https://github.com/MorphiaOrg/morphia/files/6002878/reproducer-master.zip)

**Comment by evanchooly** [comment]
It wasn't the static-ness of the field.  It was the wildcard.  Though there's a test already for wildcards on fields, this one apparently hit a slightly different code path resulting in the error.  I have it fixed for 2.1.5, though.
