### ISSUE TITLE
Why Decoder Can Not Be Null?

### ISSUE THREAD

**Issue by iAmcR** [MorphiaOrg/morphia#1580]
Hi, I'm trying to figure out why when querying/iterating a model/entity, I'm getting decoder can not be null as shown in the below stack trace? Other entities work, but this particular one isn't so I'm trying to figure out why it isn't working.  Any ideas?

```
Caused by: java.lang.IllegalArgumentException: decoder can not be null
	at org.bson.assertions.Assertions.notNull(Assertions.java:35)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:95)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:65)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:87)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:42)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:47)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:412)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:308)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:500)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:224)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220)
	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:631)
	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:625)
	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:462)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:625)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:77)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:320)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:201)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:196)
```

    Server Version: MongoDB, 4.0.22
    Driver Version: mongo-java-driver|sync, version: "4.0.5" 
    Morphia Version: morphia-core, 2.1.4

   Note: It is a single node replication cluster using Wired Tiger storage engine.

**Comment by evanchooly** [comment]
I'm guessing it's finding a document type that isn't mapped.  Check the `className` fields in those documents and see if you have something in your database that you haven't mapped in your app.

**Comment by iAmcR** [comment]
Thank you. 
I see where the problem is now, but not sure how to fix it. 
The problem is because of inheritance from an abstract class. When I removed the inheritance to debug it works, but with it the above exception is thrown. 

Please note I had to do a mapExternal for that abstract class, as it's possible that its child classes can be an entity or embeddable. For example: `datastore.getMapper().mapExternal(EmbeddedBuilder.builder(), IAbstract.class);`

How would I configure Morphia to handle this?

**Comment by evanchooly** [comment]
What did the errant document look like?  I'm trying to visualize what about subclassing the abstract type would cause it to break.

**Comment by iAmcR** [comment]
Sure it's not very complex document

```
@Entity("errants")
public class Errant extends SErrant implements IBehaviours {

    @Id
    public String id;

    @Property("n")
    public String name;

    @Property("o")
    public EmbeddedObject obj;  // not a child of SErrant

    @Property("a")
    public SErrant relatedTo;

    @Property("t")
    public ErrantType type;

    @Property("c")
    public Category category;

    public enum ErrantType {
        Recoverable, Serious, Transient
    }

    @Entity("errant.categories")
    public static class Category extends Model {

        @Id
        public String id;

        @Property("d")
        public String desc;

        public Category() {
        }

        public Category(String name, String desc) {
            this.id = name;
            this.desc = desc;
        }
    }
}

```

where SErrant extends Model, which is a also an abstract class

**Comment by evanchooly** [comment]
What does the doc in the database look like?  Specifically, what's the discriminator say?  The field is probably named `className`.

**Comment by iAmcR** [comment]
Oh ok... The discriminator is actually "_t" in this version of Morphia. I was checking to ensure that it is there as knew older versions it was `className`. The document below isn't all populated as some are nulls (and no Category is set) - that's it. 

```

{
  "_id" : "58ffd8dfc1e1ef123db53987",
  "_t" : "Errant",
  "n" : "Test",
  "o" : {
    "_t" : "EmbeddedObject",
    "ct" : ISODate("2017-04-29T23:30:17Z"),
    "ut" : ISODate("2017-04-29T23:35:17Z")
  },
  "t" : "Serious",
  "ct" : ISODate("2017-04-25T23:16:47.988Z"),
  "ut" : ISODate("2021-03-03T23:36:21.433Z")
}

```

**Comment by evanchooly** [comment]
I'm curious about that `o` field.  Where it's dying, it's trying to deserialize a field value.  do you have anything mapped with a discriminator value of `EmbeddedObject`?

**Comment by iAmcR** [comment]
Hi, yes. Every class that's in `Errant` is mapped using `datastore.getMapper().map()` 

I know it's all curious and just weird.

**Comment by iAmcR** [comment]
I really do think it has something to do with the interaction of Inherited classes...  As it stands it would be:

`Errant -> SErrant -> Model`

where both SErrant and Model are abstract classes containing properties/fields and recall that SErrant can be embedded so it's mapped by `datastore.getMapper().mapExternal(EmbeddedBuilder.builder(), SErrant.class); `. 

All concrete embedded or entity classes are mapped and by rule I cannot `Model` as it's abstract and not to be stored in MongoDB. However, `SErrant` is externally mapped to be an embeddable, but its respective concrete discriminators are realized in the DB (as it should).

**Comment by iAmcR** [comment]
Hi, figured it out. It's pretty simple, I need to get some sleep! 

The problem occurred because I had the repeated the same properties in the abstract class into the concrete class. For example, I had:

```
   @Property("p")
    public int pathetic;
```  

in `Errant` and in `SErrant`. Morphia doesn't like that and couldn't determine which to use so essentially no decoder was set for that field. 

Thanks a mil for clues and pointing me in the right direction. It's very appreciated!

**Comment by evanchooly** [comment]
Wow.  It would have taken forever to suss that out here.  Nice catch.  Though it suggests I should add a test for that case.  I'm pretty sure there's a validation for conflicting mappings like that but I'm not sure it checks the cross-inheritance boundary like that.
