### ISSUE TITLE
Classloader from `MapperOptions` is not respected in `DiscriminatorLookup`

### ISSUE THREAD

**Issue by renat-nosto** [MorphiaOrg/morphia#1581]
**Describe the bug**
`MapperOptions` has a builder method to provide a `ClassLoader`, but the `dev.morphia.mapping.MapperOptions#getClassLoader` seems to be only used to populate the derived `Builder` whereas it should be used in `dev.morphia.mapping.DiscriminatorLookup#getClassForName` and `dev.morphia.mapping.Mapper#mapPackage`

Ignoring supplied classloader leads to a failure of decoding classes loaded not by system classloader

**To Reproduce**
Have an entity 
```java
@Entity
class A {
  private Base embed;
}

@Embedded
abstract class Base {
}

@Embedded
class Child extends Base {
//
}
```
Load `Base` and `Child` with non-system classloader

Get:
```
org.bson.codecs.configuration.CodecConfigurationException: Failed to decode 'Base'. Decoding errored with: A class could not be found for the discriminator: 'Child'.
	at dev.morphia.mapping.codec.pojo.EntityDecoder.getCodecFromDocument(EntityDecoder.java:110) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:45) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66) ~[morphia-core-2.1.4.jar:?]
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96) ~[bson-4.0.5.jar:?]
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:65) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:87) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:42) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:47) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66) ~[morphia-core-2.1.4.jar:?]
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[mongodb-driver-core-4.0.5.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[bson-4.0.5.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[bson-4.0.5.jar:?]
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48) ~[bson-4.0.5.jar:?]
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:101) ~[bson-4.0.5.jar:?]
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[mongodb-driver-core-4.0.5.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:84) ~[bson-4.0.5.jar:?]
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:41) ~[bson-4.0.5.jar:?]
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:412) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:308) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:258) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:99) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:500) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:224) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:343) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:334) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:220) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:631) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:625) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:462) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:625) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:77) ~[mongodb-driver-core-4.0.5.jar:?]
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190) ~[mongodb-driver-sync-4.0.5.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135) ~[mongodb-driver-sync-4.0.5.jar:?]
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92) ~[mongodb-driver-sync-4.0.5.jar:?]
	at dev.morphia.query.LegacyQuery.prepareCursor(LegacyQuery.java:468) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.query.LegacyQuery.iterator(LegacyQuery.java:270) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.query.LegacyQuery.iterator(LegacyQuery.java:265) ~[morphia-core-2.1.4.jar:?]
	at dev.morphia.query.LegacyQuery.iterator(LegacyQuery.java:38) ~[morphia-core-2.1.4.jar:?]
```

**Expected behavior**
Classloader provided in `MapperOptions`  is used consistently for loading classes across `Mapper`

** Please complete the following information: **
 - Server Version: 4.2.8
 - Driver Version: 4.0.5
 - Morphia Version: 2.1.4

**Additional context**

**Comment by Gerrygames** [comment]
This issue has been reintroduced by https://github.com/MorphiaOrg/morphia/commit/5aa7ed2a5781143ff589dabe15ec5fe918a68a48
