### ISSUE TITLE
java.lang.ClassCastException: class org.bson.types.Binary cannot be cast to class org.bson.BsonBinary

### ISSUE THREAD

**Issue by rozky** [MorphiaOrg/morphia#1599]
**Describe the bug**
Unable to read fields of type `byte[]` on embedded object after registering custom `EntityInterceptor`.

Error:
```stacktrace
java.lang.ClassCastException: class org.bson.types.Binary cannot be cast to class org.bson.BsonBinary (org.bson.types.Binary and org.bson.BsonBinary are in unnamed module of loader 'app')

	at dev.morphia.mapping.codec.reader.DocumentReader.peekBinarySize(DocumentReader.java:91)
	at org.bson.codecs.DocumentCodec.readValue(DocumentCodec.java:240)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:169)
	at org.bson.codecs.DocumentCodec.decode(DocumentCodec.java:46)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeWithLifecycle(EntityDecoder.java:124)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:38)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:66)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:87)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeWithLifecycle(EntityDecoder.java:144)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:38)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:477)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:367)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:280)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:490)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:255)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:345)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:336)
	at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:222)
	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:656)
	at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:650)
	at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:582)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:650)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:78)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:178)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:320)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:201)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:184)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:179)
	at MorphiaTest.findById(MorphiaTest.java:78)
```

**To Reproduce**

Here is custom test that should end up in the above error:
```java
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.bson.types.ObjectId;
import org.junit.jupiter.api.Test;
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;
import com.mongodb.MongoCredential;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.client.model.Filters;

import static com.mongodb.MongoCredential.createCredential;
import dev.morphia.Datastore;
import dev.morphia.EntityInterceptor;
import dev.morphia.Morphia;
import dev.morphia.annotations.Embedded;
import dev.morphia.annotations.Entity;
import dev.morphia.annotations.Id;
import static dev.morphia.query.experimental.filters.Filters.eq;
import static java.lang.String.format;
import static java.nio.charset.StandardCharsets.UTF_8;

public class MorphiaTest {
    private static final byte[] BYTES = "bytes".getBytes(UTF_8);

    @Entity(RootEntity.COLLECTION_NAME)
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder
    @Data
    public static class RootEntity {
        private static final String COLLECTION_NAME = "root-entity";
        @Id
        private ObjectId id;
        private byte[] bytes;
        private NestedEntity nested;
    }

    @Embedded
    @AllArgsConstructor
    @NoArgsConstructor
    @Builder
    @Data
    public static class NestedEntity {
        private byte[] bytes;
    }

    private static final String DATABASE = "morphia2115";
    private static MongoClient mongoClient = createMongoClient(DATABASE, "root", "example");
    private static Datastore datastore = createDatastore(mongoClient, DATABASE);

    @Test
    void shouldWriteAndReadDocumentSuccessfully() {

        RootEntity entity = RootEntity.builder()
                .id(ObjectId.get())
                .bytes(BYTES)
                .nested(NestedEntity.builder().bytes(BYTES).build())
                .build();

        // when
        save(entity);

        // then
        System.out.println(findById(entity.id));
        System.out.println(findByIdUsingMongoClient(entity.id));
    }

    private void save(RootEntity entity) {
        datastore.insert(entity);
    }

    private RootEntity findById(ObjectId id) {
        return datastore.find(RootEntity.class).filter(eq("_id", id)).first();
    }

    private RootEntity findByIdUsingMongoClient(ObjectId id) {
        return datastore.getDatabase()
                .getCollection(RootEntity.COLLECTION_NAME)
                .find(RootEntity.class)
                .filter(Filters.eq("_id", id))
                .first();
    }

    static MongoClient createMongoClient(String dbName,
                                         String username,
                                         String password) {
        ConnectionString connectionString = new ConnectionString(format("mongodb://%s/%s", "localhost", dbName));

        MongoCredential credential = createCredential(username, "admin", password.toCharArray());

        MongoClientSettings mongoClientSettings = MongoClientSettings.builder()
                .applyConnectionString(connectionString)
                .credential(credential)
                .build();

        return MongoClients.create(mongoClientSettings);
    }

    static Datastore createDatastore(MongoClient mongoClient,
                                     String database) {
        Datastore datastore = Morphia.createDatastore(mongoClient, database);
        datastore.getMapper().mapPackage(RootEntity.class.getPackage().getName());
        datastore.getMapper().addInterceptor(new EntityInterceptor() {});

        return datastore;
    }
}
```

**Expected behavior**
No exception should be throw and entity should be read from db correctly.

** Please complete the following information: **
 - Server Version: 4.4
 - Driver Version: 4.1.0
 - Morphia Version: 2.1.15

**Additional context**

A few observations:
* If I comment out `datastore.getMapper().addInterceptor(new EntityInterceptor() {});` then error goes away. Our actual interceptor is more complex but errors appears even with vanilla interceptor
* If I comment out `.nested(NestedEntity.builder().bytes(BYTES).build())` then error goes away

**Comment by rozky** [comment]
Looking deeper into the issue it looks similar to https://github.com/MorphiaOrg/morphia/issues/1548
In `DocumentReader` there are 3 kind of related methods: `readBinaryData`, `peekBinarySubType`, `peekBinarySize`. 2 of them already handle `Binary` but `peekBinarySize` doesn't.

**Comment by evanchooly** [comment]
fixed by PR

**Comment by evanchooly** [comment]
There might not be a 2.1.6.  I'm close enough to a 2.2.0 that I might just wait to push it with this. or i might not.  releases are cheap.  I'll take a look at what's left in 2.2.0 tonight and see.

**Comment by rozky** [comment]
Thanks a lot, 2.1.6 would be a big help if it's easy.
