### ISSUE TITLE
Issues converting to 2.x

### ISSUE THREAD

**Issue by ctmay4** [MorphiaOrg/morphia#1611]
I have been running on Morphia for many years.  I am trying to migrate my codebase from 1.6.x to 2.1 and am running into some issues.  Primarily I cannot get it to initialize.  In 1.6, I initialized like this:

```java
Morphia morphia = new Morphia();

// auto-embedded indices are going away; this removed the warning messages in log
morphia.getMapper().getOptions().setDisableEmbeddedIndexes(true);

morphia.map(UserBean.class);
morphia.map(RequestBean.class);
morphia.map(PasswordResetBean.class);
morphia.map(NdcProduct.class);
morphia.map(Hcpcs.class);
morphia.map(LookupBean.class);
morphia.map(DiseaseBean.class);
morphia.map(DiseaseVersionBean.class);
morphia.map(DiseaseChangelogBean.class);
morphia.map(RxBean.class);
morphia.map(RxVersionBean.class);
morphia.map(RxChangelogBean.class);
morphia.map(GlossaryBean.class);
morphia.map(GlossaryVersionBean.class);
morphia.map(GlossaryChangelogBean.class);
morphia.map(StagingVersion.class);
morphia.map(StagingSchema.class);
morphia.map(StagingTable.class);
morphia.map(StagingSchemaHistory.class);
morphia.map(StagingTableHistory.class);

MongoClient mongoClient = new MongoClient(new MongoClientURI(uri));

Datastore datastore = morphia.createDatastore(mongoClient, db);

datastore.ensureIndexes();
```

Looking at the documentation at https://morphia.dev/morphia/2.1/quick-tour.html, I tried to initialize 2.1 like this:

```java
Datastore datastore = Morphia.createDatastore(MongoClients.create("mongodb://localhost:27017"), "seerapi_unittest",
        MapperOptions.builder().disableEmbeddedIndexes(true).build());

datastore.getMapper().map(UserBean.class);
datastore.getMapper().map(RequestBean.class);
datastore.getMapper().map(PasswordResetBean.class);
datastore.getMapper().map(NdcProduct.class);
datastore.getMapper().map(Hcpcs.class);
datastore.getMapper().map(LookupBean.class);
datastore.getMapper().map(DiseaseBean.class);
datastore.getMapper().map(DiseaseVersionBean.class);
datastore.getMapper().map(DiseaseChangelogBean.class);
datastore.getMapper().map(RxBean.class);
datastore.getMapper().map(RxVersionBean.class);
datastore.getMapper().map(RxChangelogBean.class);
datastore.getMapper().map(GlossaryBean.class);
datastore.getMapper().map(GlossaryVersionBean.class);
datastore.getMapper().map(GlossaryChangelogBean.class);
datastore.getMapper().map(StagingVersion.class);
datastore.getMapper().map(StagingSchema.class);
datastore.getMapper().map(StagingTable.class);
datastore.getMapper().map(StagingSchemaHistory.class);
datastore.getMapper().map(StagingTableHistory.class);

datastore.ensureIndexes();
```

It fails on the first line with the following exception:

```
java.lang.ArrayStoreException: dev.morphia.mapping.codec.PrimitiveCodecRegistry

	at dev.morphia.mapping.Mapper.<init>(Mapper.java:95)
	at dev.morphia.DatastoreImpl.<init>(DatastoreImpl.java:68)
	at dev.morphia.Morphia.createDatastore(Morphia.java:48)
	at com.imsweb.seerapi.MorphiaConfigurationTest.testInit(MorphiaConfigurationTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

I assume there is a problem with one of my mappings, but I have no idea which.  I haven't changed these mapping in a long time and the only changes I made to the mappings are the following (this was done in many classes, but I am showing just one example):

Removed `noClassnameStored ` since it is no longer supported.

```java
@Entity(value = "users", noClassnameStored = true)
```

became 

```java
@Entity(value = "users")
```

Changed the `@Embedded` annotation.

```java
@Embedded("keys")
private Collection<UserKeyBean> _keys;
```

became

```java
@Property("keys")
private Collection<UserKeyBean> _keys;
```

Is there a way to determine what mapping it does not like?

On a side note, I found a typo in the documentation for "Limiting and Skipping" (https://morphia.dev/morphia/2.1/querying.html#_limiting_and_skipping). The example looks like this:

```java
   datastore.createQuery(Person.class)
    .iterator(new FindOptions()
	    .offset(1)
	    .limit(10))
```

However no `offset` method exists.  The method name is `skip` in `FindOptions`.

**Comment by evanchooly** [comment]
This is not the first time I've seen someone hit the odd `ArrayStoreException` but I can't find the other report.  I thought it was on SO but I can't find it.  I don't know if you're allowed to share your code but if you could build a reproducer I can take a look at it tonight or this weekend.  It's an intermittent thing and I haven't been able to repro it locally.  If not, i'd suggest mapping one class at a time until it fails again.  You can also pass in those classes in a List rather than individual calls.  

I'll see what I can do to make that error message more useful.  And update that docs typo.  Thanks.

**Comment by ctmay4** [comment]
Thanks.  My code is quite large.  I think I will create a test project and add the entities one-by-one to see this one is the issue.

**Comment by ctmay4** [comment]
Ok, I figured out why I was getting an error.  The issue is that I was specifying the Java driver in the `build.gradle`.

```
implementation 'org.mongodb:mongo-java-driver:3.12.8'
implementation 'dev.morphia.morphia:morphia-core:2.1.5'
```

It looks like the mongo-java-driver package name changed in 4.x so there are two versions in place.

![image](https://user-images.githubusercontent.com/444345/116734763-a492e180-a9bb-11eb-9e6a-cb50ccb9b61c.png)

When I remove the old version of the Java driver from the `build.gradle` the simple test works.

I have a lot more to clean up but this allows me to start.  The first simple unit tests are passing so I can continue now.

Thanks for helping out.

**Comment by evanchooly** [comment]
That's great!  It's an odd error to get but I'm glad you got past it.

It's important to note that Morphia is only tested on 4.0+ drivers.  It might work on older drivers but it certainly doesn't build with them.  You might run in to issues where morphia is assuming a newer driver.

**Comment by ctmay4** [comment]
When I moved to 2.1 I had no intention on staying on the old Java driver.  It was just an oversight.  I don't even know why I was specifying the driver at all.

I assume that 1.6.1 supports the old driver and 2.x moves to the new one?

**Comment by evanchooly** [comment]
the 1.6 train was actually done to support the 4.x driver.  1.5 was going to be the last of the "legacy" releases but I had several requests for the old Morphia on the new driver and so did a 1.6 release.  1.5.x and 1.6.x should be largely the same (apart from smaller [fixes](https://github.com/MorphiaOrg/morphia/releases/tag/r1.6.0)).  1.6 could probably still use the older driver.  Morphia won't have leveraged the new driver overly much but if I really needed the older driver for some reason I'd just use a Morphia 1.5 release.

**Comment by ctmay4** [comment]
Thanks that makes it clear now.

Sorry, but I have one more issue.  I am trying to execute this query in Morphia:

```javascript
db.disease.aggregate( [
 { $match : { "version" : "latest_dev" } },
 { $group: { _id: { type: "$type", status: "$status" },  _count: { $sum: 1 } } },
 { $project: {_id: 0, _type: "$_id.type", _status: "$_id.status", _count: 1} },
] )
```

I have some aggregation code that looks like this with the old library which has been working well for a while.

```java
List<SummaryCount> summaries = new ArrayList<>();
_ds.createAggregation(_beanClass)
        .match(getDatastore().createQuery(_beanClass).field("version").equal(version))
        .group(id(grouping("type"), grouping("status")), grouping("_count", accumulator("$sum", 1)))
        .project(projection("_id").suppress(), projection("_type", "_id.type"), projection("_status", "_id.status"), projection("_count"))
        .aggregate(SummaryCount.class).forEachRemaining(summaries::add);
```

However I have to convert this since running it under the new library says it doesn't support the legacy version.

I've always struggled with getting aggregations to work for me but here is what I put together based on the unit tests in your project.

```java
List<SummaryCount> summaries = _ds.aggregate(_beanClass)
        .match(eq("version", version))
        .group(Group.of(id().field("type").field("status")).field("_count", sum(value(1))))
        .project(Projection.of().suppressId().include("_type", Expressions.of()
                .field("_type", field("_id.type"))
                .field("_status", field("_id.status"))))
        .execute(SummaryCount.class)
        .toList();
```

The problem is running that query gives this error:

> org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class com.imsweb.seerapi.publishable.SummaryCount.

`SummaryCount` is a simple DTO to hold the results of the aggregation and I don't want to make it a entity.  It is never intended to be persisted. 

Am I doing something wrong?  Thanks for the help.

**Comment by ctmay4** [comment]
UPDATE:

I found out how to get the correct results.

```java
        List<Document> docs = _ds.aggregate(_beanClass)
                .match(eq("version", version))
                .group(Group.of(id().field("type").field("status")).field("_count", sum(value(1))))
                .project(Projection.of().suppressId()
                        .include("_type", field("_id.type"))
                        .include("_status", field("_id.status"))
                        .include("_count"))
                .execute(Document.class)
                .toList();
```

That works with `Document`.  

If I try to map it directly to `SummaryCount` I get the same error as above:

> org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class com.imsweb.seerapi.publishable.SummaryCount.

```java
        List<SummaryCount> summaries = _ds.aggregate(_beanClass)
                .match(eq("version", version))
                .group(Group.of(id().field("type").field("status")).field("_count", sum(value(1))))
                .project(Projection.of().suppressId()
                        .include("_type", field("_id.type"))
                        .include("_status", field("_id.status"))
                        .include("_count"))
                .execute(SummaryCount.class)
                .toList();
```

Is there a way to directly map to a list of DTOs that are not actual entities?

**Comment by evanchooly** [comment]
You'll need to mark it with `@Entity` ( or `@Embedded`) so that Morphia knows to map it out.  2.2 simplifies this a little by basically making `@Entity` the only annotation you need to use (`@Embedded` will be deprecated).  Then for those types that will never serve as queryable types (i.e., mapped to a collection), you can skip the `@Id` annotation on a field.  But that wont' be available until 2.2 is out.  ( I'm hoping in the next couple of weeks.  there's only 1 remaining issue.)

So try using `@Embedded` for now and that should resolve your issue here.  If not, we can look at next steps but I'd be surprised if it that didn't do the trick.

**Comment by ctmay4** [comment]
I didn't think of trying `@Embedded`.  It worked.  Thanks for the help!
