### ISSUE TITLE
InaccessibleObjectException on Java 16

### ISSUE THREAD

**Issue by Pugabyte** [MorphiaOrg/morphia#1618]
**Describe the bug**
```
[11:22:10] [Server thread/INFO]: [Nexus] Error while registering feature Radio
[11:22:10] [Server thread/WARN]: java.lang.reflect.InaccessibleObjectException: Unable to make field private final long java.util.UUID.mostSigBits accessible: module java.base does not "opens java.util" to unnamed module @4c7700ea
[11:22:10] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357)
[11:22:10] [Server thread/WARN]:        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
[11:22:10] [Server thread/WARN]:        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:177)
[11:22:10] [Server thread/WARN]:        at java.base/java.lang.reflect.Field.setAccessible(Field.java:171)
[11:22:10] [Server thread/WARN]:        at dev.morphia.mapping.MappedClass.discover(MappedClass.java:562)
[11:22:10] [Server thread/WARN]:        at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
[11:22:10] [Server thread/WARN]:        at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:516)
[11:22:10] [Server thread/WARN]:        at dev.morphia.internal.PathTarget.resolveField(PathTarget.java:169)
[11:22:10] [Server thread/WARN]:        at dev.morphia.internal.PathTarget.resolve(PathTarget.java:126)
[11:22:10] [Server thread/WARN]:        at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
[11:22:10] [Server thread/WARN]:        at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
[11:22:10] [Server thread/WARN]:        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
[11:22:10] [Server thread/WARN]:        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
[11:22:10] [Server thread/WARN]:        at dev.morphia.query.FieldEndImpl.equal(FieldEndImpl.java:96)
[11:22:10] [Server thread/WARN]:        at dev.morphia.query.FieldEndImpl.equal(FieldEndImpl.java:44)
[11:22:10] [Server thread/WARN]:        at eden.mongodb.MongoService.getNoCache(MongoService.java:197)
[11:22:10] [Server thread/WARN]:        at eden.mongodb.MongoService.lambda$getCache$1(MongoService.java:193)
[11:22:10] [Server thread/WARN]:        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
[11:22:10] [Server thread/WARN]:        at eden.mongodb.MongoService.getCache(MongoService.java:193)
[11:22:10] [Server thread/WARN]:        at eden.mongodb.MongoService.get(MongoService.java:156)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.features.radio.RadioFeature.setupRadios(RadioFeature.java:122)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.features.radio.RadioFeature.onStart(RadioFeature.java:60)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.framework.features.Features.lambda$register$2(Features.java:73)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.utils.TimeUtils$Timer.<init>(TimeUtils.java:17)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.framework.features.Features.register(Features.java:71)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.framework.features.Features.register(Features.java:52)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.framework.features.Features.lambda$registerAll$1(Features.java:45)
[11:22:10] [Server thread/WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.framework.features.Features.registerAll(Features.java:45)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.Nexus.lambda$onEnable$3(Nexus.java:248)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.utils.TimeUtils$Timer.<init>(TimeUtils.java:17)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.Nexus.lambda$onEnable$5(Nexus.java:245)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.utils.TimeUtils$Timer.<init>(TimeUtils.java:17)
[11:22:10] [Server thread/WARN]:        at me.pugabyte.nexus.Nexus.onEnable(Nexus.java:238)
[11:22:10] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[11:22:10] [Server thread/WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[11:22:10] [Server thread/WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[11:22:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[11:22:10] [Server thread/WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415)
[11:22:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591)
[11:22:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:281)
[11:22:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065)
[11:22:10] [Server thread/WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289)
[11:22:10] [Server thread/WARN]:        at java.base/java.lang.Thread.run(Thread.java:831)
```
Does not happen on Java 15 or lower

**To Reproduce**
Use our converter (maybe happens with default UUID converter, not sure)
```
public class UUIDConverter extends TypeConverter implements SimpleValueConverter {

	public UUIDConverter(Mapper mapper) {
		super(UUID.class);
	}

	@Override
	public Object encode(Object value, MappedField optionalExtraInfo) {
		if (value == null) return null;
		return value.toString();
	}

	@Override
	public Object decode(Class<?> aClass, Object value, MappedField mappedField) {
		if (value == null) return null;
		return UUID.fromString((String) value);
	}

}
```

 - Server Version: 4.4.4
 - Driver Version: 4.4.4
 - Morphia Version: 1.6.1
 - Java version: 16.0.1

**Comment by evanchooly** [comment]
Java 16 isn't yet supported.  I'm planning on trying to resolve the reflection restrictions in 2.3 as much as I can.  Morphia 1.6 is unlikely to see those changes, however, as experience has shown the changes necessary to be fairly extensive.
