### ISSUE TITLE
Map external interfaces without entity annotation

### ISSUE THREAD

**Issue by Foorcee** [MorphiaOrg/morphia#1626]
We are migrating from Morphia 1.6 to Morphia 2.0 and due to the changes in with the class mappings there are a few issues. We had in Morphia 1.6 a class with a map where the type is an interface. This interface then had different implentations. Since 2.0 it is now required that this interface must have an @Entity annotation. The interfaces are API classes from our project and actually don't want to have the annotation there.

If we map the classes with mapExternal, we get the following error:

```
dev.morphia.mapping.MappingException: No suitable constructor found for type: 'com.foo.MyFancyInterface'

	at dev.morphia.mapping.InstanceCreatorFactoryImpl.create(InstanceCreatorFactoryImpl.java:43)
	at dev.morphia.mapping.codec.pojo.EntityModel.getInstanceCreator(EntityModel.java:229)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.getInstanceCreator(EntityDecoder.java:47)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:34)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:40)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
	at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.decode(MorphiaMapPropertyCodecProvider.java:85)
	at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.decode(MorphiaMapPropertyCodecProvider.java:49)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:59)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:80)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:35)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:40)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)

```

Our reproducer test to this:

https://github.com/Cytooxien/reproducer_interface/

** Please complete the following information: **
    Server Version: reproducer ..
    Driver Version:  reproducer ..
    Morphia Version:  reproducer ..

**Comment by evanchooly** [comment]
My apologies for taking so long to get to this.  There's been a lot going on over here.  But the fix here is simple:  use the discriminator.  Without the discriminator, Morphia doesn't know how to deserialize those documents.  Setting the use discriminators on both types lets Morphia include the information it needs to store those objects and retrieve them.

**Comment by evanchooly** [comment]
Also, `mapExternal()` has turned out to be far more limited than I'd expected.  2.3 is set to introduce a more robust method for mapping external types.  See #1615 for more.

**Comment by evanchooly** [comment]
I'm going to close this out due to lack of activity.  Hopefully that means you found the answer you're looking for.  If not, please feel free to open a new ticket.
