### ISSUE TITLE
Occasional ConcurrentModification 

### ISSUE THREAD

**Issue by cocorossello** [MorphiaOrg/morphia#1784]
**Describe the bug**
Intermittent ConcurentModificationException, happens very occasionally

**To Reproduce**
We get this error from time to time, I can't give a reproducer

**Expected behavior**
No ConcurrentModification should be thrown

** Please complete the following information: **
 - Server Version: JDK 17
 - Driver Version: 4.41
 - Morphia Version: 2.2.3

**Additional context**

The stacktrace is:

java.util.ConcurrentModificationException: null
    at java.util.HashMap.computeIfAbsent(HashMap.java:1221)
    at dev.morphia.mapping.codec.Conversions.convert(Conversions.java:132)
    at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.lambda$encode$0(MorphiaMapPropertyCodecProvider.java:65)
    at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.document(ExpressionHelper.java:36)
    at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.encode(MorphiaMapPropertyCodecProvider.java:62)
    at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.encode(MorphiaMapPropertyCodecProvider.java:49)
    at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
    at dev.morphia.mapping.codec.pojo.EntityEncoder.writeValue(EntityEncoder.java:103)
    at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeValue(EntityEncoder.java:93)
    at dev.morphia.mapping.codec.pojo.EntityEncoder.lambda$encode$0(EntityEncoder.java:46)
    at dev.morphia.aggregation.experimental.codecs.ExpressionHelper.document(ExpressionHelper.java:36)
    at dev.morphia.mapping.codec.pojo.EntityEncoder.encode(EntityEncoder.java:33)
    at dev.morphia.mapping.codec.pojo.LifecycleEncoder.encode(LifecycleEncoder.java:35)
    at dev.morphia.mapping.codec.pojo.MorphiaCodec.encode(MorphiaCodec.java:126)
    at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
    at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
    at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:221)
    at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:187)
    at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
    at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
    at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
    at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
    at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:168)
    at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:138)
    at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:62)
    at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:326)
    at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
    at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:647)
    at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
    at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:244)
    at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:227)
    at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:127)
    at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:357)
    at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:477)
    at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:339)
    at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:260)
    at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:564)
    at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
    at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:563)
    at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:589)
    at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:562)
    at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:232)
    at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
    at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:268)
    at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:84)
    at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:212)
    at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1010)
    at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:568)
    at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:551)
    at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:510)
    at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:395)
    at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:389)
    at dev.morphia.Datastore$$OwbNormalScopeProxy0.save(dev/morphia/Datastore.java)
...

Maybe use a ConcurrentHashMap or synchronize access to that Map, WDYT?

**Comment by cocorossello** [comment]
Thanks, didn't see that
