### ISSUE TITLE
problem with upsert and sharded collection

### ISSUE THREAD

**Issue by terenceq** [MorphiaOrg/morphia#1872]
After updating from MongoDB 4.0.x to 4.2.x I'm observing the following errors while saving a document:

```
arget upsert by query :: could not extract exact shard key'
com.mongodb.WriteConcernException: Write failed with error code 61 and error message 'Failed to target upsert by query :: could not extract exact shard key'
	at com.mongodb.internal.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:191)
	at com.mongodb.internal.operation.BaseWriteOperation.execute(BaseWriteOperation.java:153)
	at com.mongodb.internal.operation.BaseWriteOperation.execute(BaseWriteOperation.java:53)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:195)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:164)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:346)
	at com.mongodb.DBCollection.update(DBCollection.java:577)
	at dev.morphia.DatastoreImpl.saveDocument(DatastoreImpl.java:1347)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:1296)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:773)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:756)
```

The MongoDB instance is a shared cluster and the document that is being saved is in a collection that defines two shard keys. I'm assuming this is related to these changes in MongoDB 4.2:

https://www.mongodb.com/docs/manual/release-notes/4.2-compatibility/#sharded-collections-and-replace-documents

```
For a replace document operation that includes upsert: true and is on a sharded collection, the filter must include an equality match on the full shard key.
```

For now I'm stuck on Morphia 1.6.1 and it looks like the problem is here:

https://github.com/MorphiaOrg/morphia/blob/r1.6.1/morphia/src/main/java/dev/morphia/DatastoreImpl.java#L1347

Only one field attribute identified by `ID_FIELD_NAME` is used in the filter for the upsert operation. So this is more of a question: would moving to Morphia 2.x resolve this automatically or would I need to following what is documented here:

https://morphia.dev/morphia/2.2/updates.html#_upserts

 Server Version: 4.2.19
 Driver Version: 4.1.2
 Morphia Version: 1.6.1

**Comment by evanchooly** [comment]
2.x would still require your filter to meet the server requirements.  I try to keep that kind of magic to a minimum because it leads to odd complexity in strange places.

**Comment by terenceq** [comment]
Thanks for the quick reply - I assume that I will need to use the following approach when updating a sharded collection on MongoDB v4.2.x+

```java
datastore
    .find(Hotel.class)
    .filter(gt("stars", 100))
    .update()
    .execute(new UpdateOptions()
                     .upsert(true));
```

The filter will need to contain the complete shard key for the collection.

**Comment by evanchooly** [comment]
Yep.  That should do it.
