### ISSUE TITLE
Running: morphia/example/QuickTour.java

### ISSUE THREAD

**Issue by NOTiFYcouk** [MorphiaOrg/morphia#1873]
Trying again to run:

`morphia-master/examples/src/test/java/dev/morphia/example/QuickTour.java
`

From: IntelliJ IDEA 2022.1 (Ultimate Edition) with 'Run' on 'macOS Monterey 12.3.1'

Using:

```
/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk

implementation("org.mongodb:mongodb-driver-core:4.2.3") &
implementation("org.mongodb:mongodb-driver-core:4.6.0")

implementation("org.mongodb:bson:4.2.3") &
implementation("org.mongodb:bson:4.6.0")
 
implementation("dev.morphia.morphia:morphia-core:2.3.0-SNAPSHOT")
```
Code:
```
 public static void main(String[] args) {
        final Datastore datastore = Morphia.createDatastore(MongoClients.create(), "morphia_example");

        // tell morphia where to find your classes
        // can be called multiple times with different packages or classes
        datastore.getMapper().mapPackage("dev.morphia.example");

        // create the Datastore connecting to the database running on the default port on the local host
        datastore.getDatabase().drop();
        datastore.ensureIndexes();

        final Employee elmer = new Employee("Elmer Fudd", 50000.0);
        System.out.println(">>>>> elmer getName = " + elmer.getName());
        System.out.println(">>>>> elmer getSalary = " + elmer.getSalary());
        datastore.save(elmer);

        ......
```

Get:

```
/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
>>>>> elmer getName = Elmer Fudd
>>>>> elmer getSalary = 50000.0
Exception in thread "main" java.lang.NoSuchMethodError: 'com.mongodb.client.result.InsertOneResult com.mongodb.client.MongoCollection.insertOne(java.lang.Object, com.mongodb.client.model.InsertOneOptions)'
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:611)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:450)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:444)
	at example.QuickTour.main(QuickTour.java:34)
```

**Comment by NOTiFYcouk** [comment]
In MongoDB create new version:

`>>>>> datastore getDatabase getName = morphia_example`

With:

/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk/Contents/Home/bin/java
implementation("dev.morphia.morphia:morphia-core:2.3.0-SNAPSHOT")
MongoDB shell version v5.0.7

When I run: 

```
Exception in thread "main" java.lang.ClassCastException: class dev.morphia.mapping.codec.PrimitiveCodecRegistry cannot be cast to class org.bson.codecs.configuration.CodecProvider (dev.morphia.mapping.codec.PrimitiveCodecRegistry and org.bson.codecs.configuration.CodecProvider are in unnamed module of loader 'app')
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:56)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:39)
	at org.bson.Document.toBsonDocument(Document.java:114)
	at com.mongodb.internal.operation.Operations.toBsonDocument(Operations.java:539)
	at com.mongodb.internal.operation.Operations.createIndexes(Operations.java:467)
	at com.mongodb.internal.operation.SyncOperations.createIndexes(SyncOperations.java:225)
	at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:891)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:874)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:869)
	at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:854)
	at dev.morphia.annotations.IndexHelper.createIndex(IndexHelper.java:161)
	at dev.morphia.annotations.IndexHelper.createIndex(IndexHelper.java:151)
	at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:215)
	at dev.morphia.example.QuickTour.main(QuickTour.java:32)

Process finished with exit code 1
```

Code was:

```
package dev.morphia.example;

import com.mongodb.client.MongoClients;
import dev.morphia.Datastore;
import dev.morphia.Morphia;
import dev.morphia.query.Query;
import static org.testng.AssertJUnit.assertEquals;

/**
 * This class is used in the Quick Tour documentation and is used to demonstrate various Morphia features.
 */

/**
 * This class is used in the Quick Tour documentation and is used to demonstrate various Morphia features.
 */
public final class QuickTour {

    private QuickTour() {
    }

    public static void main(String[] args) {
        final Datastore datastore = Morphia.createDatastore(MongoClients.create(), "morphia_example");
        System.out.println(">>>>> datastore = " + datastore);
        System.out.println(">>>>> datastore getDatabase getName = " + datastore.getDatabase().getName());

        // tell morphia where to find your classes
        // can be called multiple times with different packages or classes
        datastore.getMapper().mapPackage("dev.morphia.example");

        // create the Datastore connecting to the database running on the default port on the local host
        datastore.getDatabase().drop();
        datastore.ensureIndexes();

        final Employee elmer = new Employee("Elmer Fudd", 50000.0);
        System.out.println(">>>>> 1.1 elmer getName = " + elmer.getName());
        System.out.println(">>>>> 1.2 elmer getSalary = " + elmer.getSalary());
        datastore.save(elmer);

        final Employee daffy = new Employee("Daffy Duck", 40000.0);
        System.out.println(">>>>> 2.1 elmer getName = " + elmer.getName());
        System.out.println(">>>>> 2.2 elmer getSalary = " + elmer.getSalary());
        datastore.save(daffy);

        final Employee pepe = new Employee("Pepé Le Pew", 25000.0);
        System.out.println(">>>>> 3 elmer getName = " + elmer.getName());
        System.out.println(">>>>> 3 elmer getSalary = " + elmer.getSalary());
        datastore.save(pepe);

        elmer.getDirectReports().add(daffy);
        elmer.getDirectReports().add(pepe);
        System.out.println(">>>>> 4 elmer getName = " + elmer.getName());
        System.out.println(">>>>> 4 elmer getSalary = " + elmer.getSalary());

        datastore.save(elmer);

        Query<Employee> query = datastore.find(Employee.class);
        final long employees = query.count();

        assertEquals(employees, 3);

//        long underpaid = datastore.find(Employee.class)
//            .filter(lte("salary", 30000))
//            .count();
//        assertEquals(underpaid, 1);

//        final Query<Employee> underPaidQuery = datastore.find(Employee.class)
//            .filter(lte("salary", 30000));
//        final UpdateResult results = underPaidQuery.update(inc("salary", 10000))
//            .execute();

//        assertEquals(results.getModifiedCount(), 1);

//        datastore.find(Employee.class)
//            .filter(gt("salary", 100000))
//            .findAndDelete();
    }
}
```

**Comment by evanchooly** [comment]
I just ran this on `master` and it ran just fine.  If you could put together a [reproducer](/morphiaorg/reproducer) I'd be happy to take a look and see.

**Comment by NOTiFYcouk** [comment]
The work to build & run 'https://github.com/morphiaorg/reproducer' seems a lot of effort to run the 'dev.morphia.example'. I run all my test on Intellij & Gradle. 

I've spend 10 days with 'morphiaorg' and happy to invest more time & effort but need some pointers.

**Comment by evanchooly** [comment]
well, i just opened up the project in IDEA and clicked the run button.  If you're doing something with gradle that means you have a different environment set up and I can't test that from here.  But via maven as set up in the github repo it seems to work just fine.

**Comment by NOTiFYcouk** [comment]
Just done as you suggested and loaded "morphia-master" and has run okay.

```
/Library/Java/JavaVirtualMachines/jdk-17.0.2.jdk
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Process finished with exit code 0
```
MongoDB:

```
_id
627bea5bc04b35570c092759
_t
"Employee"
name
"Elmer Fudd"

directReports
Array
wage
50000
_id
627bea5bc04b35570c09275a
_t
"Employee"
name
"Daffy Duck"
wage
40000
_id
627bea5bc04b35570c09275b
_t
"Employee"
name
"Pepé Le Pew"
wage
35000
```
As you suggested must be an issue in my Gradle build. 

I'll start to attempt migrate from working MongoDB Hibernate OGM, ORM & Mongodb Java driver directly to 'Morphia'

Thanks for your support.

**Comment by evanchooly** [comment]
Absolutely.  I'm happy to help.  If you have questions, don't forget the [Discussions](https://github.com/MorphiaOrg/morphia/discussions) feature which might be better suited for back and forth dialogs.  Either way, please don't hesitate to ask and I'll try to get you sorted.
