### ISSUE TITLE
ReferenceException when trying to persist a reference list with duplicated entries

### ISSUE THREAD

**Issue by isaacrj** [MorphiaOrg/morphia#2012]
**Describe the bug**
When persiting an entity with a reference list that contains duplicated entries, a ReferenceException is thrown:

``` 
dev.morphia.mapping.lazy.proxy.ReferenceException: Referenced 'ChildEntity' entities could not be found during a fetch.
	at dev.morphia.mapping.experimental.CollectionReference.query(CollectionReference.java:167)
	at dev.morphia.mapping.experimental.CollectionReference.find(CollectionReference.java:143)
```

This is the relevant part of dev.morphia.mapping.experimental.CollectionReference:

```
Map<Object, Object> query(String collection, List<Object> collectionIds) {

        final Map<Object, Object> idMap = new HashMap<>();
        try (MongoCursor<?> cursor = getDatastore().find(collection)
                                                   .disableValidation()
                                                   .filter(in("_id", collectionIds)).iterator()) {
            while (cursor.hasNext()) {
                final Object entity = cursor.next();
                idMap.put(getDatastore().getMapper().getId(entity), entity);
            }

            if (!ignoreMissing() && idMap.size() != collectionIds.size()) {
                throw new ReferenceException(
                    Sofia.missingReferencedEntities(entityModel.getType().getSimpleName()));

            }
        }

        return idMap;
    }
```

It seems that comparing idMap.size() and collectionIds.size() is not a correct way to detect missing references, as duplicated ids on collectionIds won't yield duplicated entries on the Map and the size() comparisong will fail.

Maybe it could be solved by using a Set for the collectionIds, thus having them deduplicated before comparing sizes.

**Comment by evanchooly** [comment]
I just pushed 2.2.9 with this fix.  If it's not already on central by now it should be in an hour or two.

**Comment by isaacrj** [comment]
Thanks a lot, guys
