### ISSUE TITLE
ArrayIndexOutOfBoundsException from MorphiaQuery.iterator and DatastoreImpl.save

### ISSUE THREAD

**Issue by leandroutn** [MorphiaOrg/morphia#2140]
**Describe the bug**
We're (sometimes) getting `ArrayIndexOutOfBoundsException` from `MorphiaQuery.iterator` and `DatastoreImpl.save`

**To Reproduce**
Not sure TBH, seems to have some concurrency involved

**Expected behavior**
`MorphiaQuery.iterator` and `DatastoreImpl.save` shouldn't throw `ArrayIndexOutOfBoundsException`

** Please complete the following information: **
Morphia Version: 2.1.5 (based on the code, seems to still exists within the latest, 2.2.8)
Server Version: 4.2
Driver Version: 4.7.1

**Additional context**
```
java.lang.ArrayIndexOutOfBoundsException: Index 11 out of bounds for length 10
	at java.base/java.util.ArrayList.add(ArrayList.java:455)
	at java.base/java.util.ArrayList.add(ArrayList.java:467)
	at dev.morphia.mapping.codec.pojo.EntityModel.addSubtype(EntityModel.java:370)
	at dev.morphia.mapping.codec.pojo.EntityModel.<init>(EntityModel.java:103)
	at dev.morphia.mapping.codec.pojo.EntityModelBuilder.build(EntityModelBuilder.java:173)
	at dev.morphia.mapping.Mapper.createEntityModel(Mapper.java:503)
	at dev.morphia.mapping.Mapper.getEntityModel(Mapper.java:129)
	at dev.morphia.mapping.codec.MorphiaCodecProvider.get(MorphiaCodecProvider.java:48)
	at dev.morphia.mapping.codec.MorphiaCodecProvider.get(MorphiaCodecProvider.java:23)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:45)
	at org.bson.internal.OverridableUuidRepresentationCodecRegistry.get(OverridableUuidRepresentationCodecRegistry.java:55)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:58)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:57)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:39)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeWithLifecycle(EntityDecoder.java:131)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:38)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:66)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:87)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeWithLifecycle(EntityDecoder.java:144)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:38)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:66)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:535)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:420)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:337)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:240)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:226)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:126)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:116)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:345)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:232)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:695)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$2(OperationHelper.java:566)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:591)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$3(OperationHelper.java:565)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:591)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:564)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:690)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:65)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:722)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:86)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:320)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:201)
	...
```
and
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/java.util.ArrayList.add(ArrayList.java:487)
	at java.base/java.util.ArrayList.add(ArrayList.java:499)
	at dev.morphia.mapping.codec.pojo.EntityModel.addSubtype(EntityModel.java:370)
	at dev.morphia.mapping.codec.pojo.EntityModel.<init>(EntityModel.java:103)
	at dev.morphia.mapping.codec.pojo.EntityModelBuilder.build(EntityModelBuilder.java:173)
	at dev.morphia.mapping.Mapper.createEntityModel(Mapper.java:503)
	at dev.morphia.mapping.Mapper.getEntityModel(Mapper.java:129)
	at dev.morphia.mapping.Mapper.getCollection(Mapper.java:266)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:394)
	...
```

**Comment by evanchooly** [comment]
I'm a little surprised to see that error given how old it at this point but I just pushed an update that uses the COW list.  Once CI has had a chance to run, if you wan't to give `2.2.10-SNAPSHOT` a go to confirm it fixes your issue, I can push that release out.

**Comment by evanchooly** [comment]
I just pushed 2.2.10.  It should be ready in maven central in an hour or two.
