### ISSUE TITLE
Morphia doesn't check the actual key type for subclasses of Map

### ISSUE THREAD

**Issue by emandirola** [MorphiaOrg/morphia#2447]
**Describe the bug**
Subclassing `Map` and hardcoding the key type breaks `MapKeyTypeConstraint` and `MorphiaMapPropertyCodecProvider`.

**To Reproduce**
1. Create a subclass of `Map<K, V>` with a hardcoded key, for example: `MyMap<V> extends HashMap<String, V>`
2. Run the app
3. Check that it errors with `Maps must be keyed by a simple type (Map<String/Enum/Long/ObjectId/..., ?>);` when it's actually a String

**Expected behavior**
`MapKeyTypeConstraint` and `MorphiaMapPropertyCodecProvider` check the actual key type by bubbling up to `Map` (I guess) instead of assuming the first type parameter of the final class is the key.

** Please complete the following information: **
 - Server Version: N/A
 - Driver Version: N/A
 - Morphia Version: 2.3.5

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

Repro repo: https://github.com/emandirola/morphia-bug-MapKeyTypeConstraint/

<details>
<summary>MapKeyTypeConstraint stacktrace</summary>

```
dev.morphia.mapping.validation.ConstraintViolationException: Number of violations: 1 
MapKeyTypeConstraint complained about com.foo.MapWithListBuggedmap. : Maps must be keyed by a simple type (Map<String/Enum/Long/ObjectId/..., ?>); interface java.util.List is not supported as a map key type.

	at dev.morphia.mapping.validation.MappingValidator.validate(MappingValidator.java:59)
	at dev.morphia.mapping.Mapper.register(Mapper.java:484)
	at dev.morphia.mapping.Mapper.getEntityModel(Mapper.java:210)
	at dev.morphia.DatastoreImpl.getCollection(DatastoreImpl.java:320)
	at dev.morphia.DatastoreImpl.insert(DatastoreImpl.java:152)
	at dev.morphia.Datastore.insert(Datastore.java:333)
	at com.foo.ReproducerTest.brokenSaveWithList(ReproducerTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```
</details>

<details>
<summary>MorphiaMapPropertyCodecProvider stacktrace</summary>

```
java.lang.NumberFormatException: For input string: "key"

	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at dev.morphia.mapping.codec.Conversions.convert(Conversions.java:165)
	at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.decode(MorphiaMapPropertyCodecProvider.java:81)
	at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.decode(MorphiaMapPropertyCodecProvider.java:50)
	at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:62)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:83)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:42)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76)
	at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:47)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76)
	at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at org.bson.internal.LazyCodec.decode(LazyCodec.java:53)
	at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
	at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
	at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:50)
	at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:538)
	at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:423)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:340)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:116)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:643)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:206)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:119)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:85)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:75)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:293)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:233)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:332)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:356)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:355)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:381)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:354)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:329)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:340)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:79)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:191)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:133)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:372)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:228)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:200)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:195)
	at com.foo.ReproducerTest.brokenReadWithAnything(ReproducerTest.java:56)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
	at org.testng.SuiteRunner.run(SuiteRunner.java:330)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
	at org.testng.TestNG.runSuites(TestNG.java:1099)
	at org.testng.TestNG.run(TestNG.java:1067)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
```
</details>

Note: I found out about `MorphiaMapPropertyCodecProvider` while making the repro.

**Comment by evanchooly** [comment]
fixed in d620cf26edb8fbf9c414b1fcce84d69b6e4bac23
