### ISSUE TITLE
IllegalStateException due to implicit re-use of client session

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#2488]
**Describe the bug**

In Morphia v2.2.x, multi-document transactions did work fine for us. But starting with Morphia v2.3.0 and even with latest v2.4.x release of Morphia, we encounter `IllegalStateException`s now and then like the following:
```
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:81)
	at com.mongodb.internal.session.BaseClientSessionImpl.getServerSession(BaseClientSessionImpl.java:124)
	at com.mongodb.internal.session.ClientSessionContext.getSessionId(ClientSessionContext.java:48)
	at com.mongodb.internal.connection.ClusterClockAdvancingSessionContext.getSessionId(ClusterClockAdvancingSessionContext.java:50)
	at com.mongodb.internal.connection.CommandMessage.getExtraElements(CommandMessage.java:230)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:155)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:136)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:719)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:203)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:287)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:245)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:324)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:345)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:344)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:343)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:321)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$decorateReadWithRetries$3(CommandOperationHelper.java:192)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:332)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:72)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:374)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:229)
	at dev.morphia.query.Query.iterator(Query.java:281)

```  
It seems that the client-session used by a multi-document transaction is somehow re-used by the query although the transaction has already ended and the query is not performed in any transaction at all.

 
**To Reproduce**
Run the following test with latest 2.4.x release: 

```java
package dev.morphia.test.mapping.lazy;

import com.mongodb.client.result.DeleteResult;

import dev.morphia.annotations.Reference;
import dev.morphia.query.filters.Filters;
import dev.morphia.test.mapping.ProxyTestBase;
import dev.morphia.test.models.TestEntity;

import org.bson.types.ObjectId;
import org.testng.Assert;
import org.testng.annotations.Test;

@Test(groups = "references")
public class TestTransactional extends ProxyTestBase
{
    @Test
    public void testFetchAfterTransactionalDelete()
    {
        checkForProxyTypes();
        checkForReplicaSet();

        RootEntity root = new RootEntity();
        final ReferencedEntity ref = new ReferencedEntity();
        ref.setFoo("bar");

        root.r = ref;

        final ObjectId refId = getDs().save(ref).getId();
        final ObjectId rootId = getDs().save(root).getId();

        root = getDs().find(RootEntity.class).filter(Filters.eq("_id", rootId)).first();
        final ReferencedEntity p = root.r;
        assertIsProxy(p);
        assertNotFetched(p);

        final DeleteResult deleteResult = getDs().withTransaction((session) -> session.find(RootEntity.class).delete());
        Assert.assertEquals(deleteResult.getDeletedCount(), 1);

        Assert.assertEquals(root.getR().getId(), refId);
    }

    public static class RootEntity extends TestEntity
    {

        @Reference(lazy = true)
        private ReferencedEntity r;

        public void setR(ReferencedEntity r)
        {
            this.r = r;
        }

        public ReferencedEntity getR()
        {
            return r;
        }
    }

    public static class ReferencedEntity extends TestEntity
    {
        private String foo;

        public String getFoo()
        {
            return foo;
        }

        public void setFoo(String foo)
        {
            this.foo = foo;
        }
    }
}
```
Unfortunately. I don't have a demo test for Morphia v2.3.x;  the one cited above passes for Morphia v2.3.7. But the very same exception is thrown in our app now and then when a multi-document transaction was performed before.
 
**Expected behavior**
Unit test passes.

** Please complete the following information: **
 - Server Version: 6.0
 - Driver Version: 4.9.0
 - Morphia Version: 2.4.1

**Comment by evanchooly** [comment]
Can you try with 2 4.2 that was just released last night?

**Comment by h-arlt** [comment]
Ran the test using Morphia v2.4.2 and issue is still present.

**Comment by h-arlt** [comment]
As for Morphia v2.3.7, I got a stack trace for the same exception that seems to be caused by `SingleReference` referencing a `MorphisSessionImpl` instance as datastore created by some former transaction. I'm still puzzled how this can happen. So, it's hard for me to provide a reproducible test case.

As far as I understand the code, the datastore is passed from the codec to the `SingleRefence`. Thus, the codec must have been initialized with the `MorphiaSessionImpl` instance. 
 
```
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:81)
	at com.mongodb.internal.session.BaseClientSessionImpl.getServerSession(BaseClientSessionImpl.java:124)
	at com.mongodb.internal.session.ClientSessionContext.getSessionId(ClientSessionContext.java:48)
	at com.mongodb.internal.connection.ClusterClockAdvancingSessionContext.getSessionId(ClusterClockAdvancingSessionContext.java:50)
	at com.mongodb.internal.connection.CommandMessage.getExtraElements(CommandMessage.java:230)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:155)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:136)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:719)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:203)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:287)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:245)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:324)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:345)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:344)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:343)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:321)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$decorateReadWithRetries$3(CommandOperationHelper.java:192)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:332)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:72)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:372)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:228)
	at dev.morphia.query.Query.iterator(Query.java:281)
	at dev.morphia.mapping.experimental.SingleReference.get(SingleReference.java:85)
	at dev.morphia.mapping.codec.references.ReferenceProxy.fetch(ReferenceProxy.java:80)
	at dev.morphia.mapping.codec.references.ReferenceProxy.invoke(ReferenceProxy.java:41)
	at Car$owner$$ReferenceProxy.unwrap(Unknown Source)
	at dev.morphia.mapping.codec.pojo.PropertyModel.getValue(PropertyModel.java:233)
	at dev.morphia.mapping.Mapper.getId(Mapper.java:231)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encodeId(ReferenceCodec.java:302)
	at dev.morphia.mapping.codec.references.ReferenceCodec.collectIdValues(ReferenceCodec.java:260)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encode(ReferenceCodec.java:220)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.writeValue(EntityEncoder.java:134)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeValue(EntityEncoder.java:108)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeProperty(EntityEncoder.java:74)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.lambda$encode$0(EntityEncoder.java:52)
	at dev.morphia.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:81)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encode(EntityEncoder.java:39)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.encode(MorphiaCodec.java:81)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:216)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:182)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:162)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:136)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:719)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:203)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:295)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:395)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:259)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:203)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:345)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:344)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:343)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:188)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$decorateWriteWithRetries$0(MixedBulkWriteOperation.java:146)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:207)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:77)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:173)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1024)
	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
	at dev.morphia.DatastoreImpl$CollectionOperations.replaceOne(DatastoreImpl.java:928)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:729)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:627)
	at dev.morphia.Datastore.save(Datastore.java:527)
```

Don't know if I'm right about the cause in Morphia v2.4.x, but it seems that the "original" datastore is not restored when the transaction ends. Letting MorphiaSessionImpl wrap the original datastore (instead of subclassing DatastoreImpl) and unwrap it when transaction ends might be a feasible approach. WDYT?

**Comment by h-arlt** [comment]
After playing around a while, I was able to create reproducible test case for Morphia 2.3.7; just add it to the test class at top of this issue.

The code might look a bit awkward at first glance but I had to clear the datastore's runtime data somehow; more specifically, the cached entity models and the respective codecs. But this was necessary to mimic a fresh start once DB has the desired state: user starts with a fresh new datastore that connects to a DB containing some data.

```java
    @Test
    public void testSaveAfterTransactionalFetch() throws Exception {
        checkForProxyTypes();
        checkForReplicaSet();

        // Preparations START
        // (1) Insert required entities into DB
        // (2) Clear any cached runtime data of datastore (entity models and their codecs)

        RootEntity root = new RootEntity();
        final ReferencedEntity ref = new ReferencedEntity();
        ref.setFoo("bar");

        root.r = ref;

        final ObjectId refId = getDs().save(ref).getId();
        final ObjectId rootId = getDs().save(root).getId();

        final Field entitiesCollField = getDs().getMapper().getClass().getDeclaredField("mappedEntities");
        entitiesCollField.setAccessible(true);

        final Map<?, ?> entitiesMap = (Map<?, ?>) entitiesCollField.get(getDs().getMapper());
        entitiesMap.clear();

        final Field entitiesCollField2 = getDs().getMapper().getClass().getDeclaredField("mappedEntitiesByCollection");
        entitiesCollField2.setAccessible(true);

        final Map<?, ?> entitiesMap2 = (Map<?, ?>) entitiesCollField2.get(getDs().getMapper());
        entitiesMap2.clear();

        final ProvidersCodecRegistry registry = (ProvidersCodecRegistry) getDs().getCodecRegistry();
        final Field codecProvidersField = registry.getClass().getDeclaredField("codecProviders");
        codecProvidersField.setAccessible(true);

        final List<CodecProvider> codecProviders = (List<CodecProvider>) codecProvidersField.get(registry);
        for (final CodecProvider provider : codecProviders) {
            if (provider instanceof MorphiaCodecProvider) {
                final MorphiaCodecProvider mcp = (MorphiaCodecProvider) provider;
                final Field f = MorphiaCodecProvider.class.getDeclaredField("codecs");
                f.setAccessible(true);

                ((Map<?, ?>) f.get(mcp)).clear();
            }
        }

        // Preparations END

        root = getDs().withTransaction((session) -> session.find(RootEntity.class)
                .filter(Filters.eq("r", session.find(ReferencedEntity.class).filter(Filters.eq("_id", refId)).first())).first());

        final ReferencedEntity p = root.r;
        assertIsProxy(p);
        assertNotFetched(p);

        root.setBar("foo");
        getDs().save(root);

        Assert.assertEquals(root.getId(), rootId);
    }
```

**Comment by evanchooly** [comment]
I thought this was going to be gnarly but it turned out not so much.

**Comment by evanchooly** [comment]
Could you open a new issue for 2.3.7?  And take a look at `withConfig()` on `TestBase` for getting a "fresh" `Datastore` and mapping information.  It would dramatically simplify your test case here.

**Comment by h-arlt** [comment]
> And take a look at `withConfig()` on `TestBase` for getting a "fresh" `Datastore` and mapping information. It would dramatically simplify your test case here.

Couldn't find the method you've stated; did you mean "withClient"?

**Comment by evanchooly** [comment]
hrm.  that method might be new in the 2.4 line.  no worries.

**Comment by h-arlt** [comment]
Fix works like a charm; did not encounter any IllegalStateExceptions any more :tada:  Thanks!!!
