### ISSUE TITLE
IllegalStateException in Morphia v2.3.7 due to re-use of client session

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#2509]
**Describe the bug**
Starting with Morphia v2.3.0, we encounter IllegalStateExceptions now and then like the following:
```
java.lang.IllegalStateException: state should be: open
	at com.mongodb.assertions.Assertions.isTrue(Assertions.java:81)
	at com.mongodb.internal.session.BaseClientSessionImpl.getServerSession(BaseClientSessionImpl.java:124)
	at com.mongodb.internal.session.ClientSessionContext.getSessionId(ClientSessionContext.java:48)
	at com.mongodb.internal.connection.ClusterClockAdvancingSessionContext.getSessionId(ClusterClockAdvancingSessionContext.java:50)
	at com.mongodb.internal.connection.CommandMessage.getExtraElements(CommandMessage.java:230)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:155)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:136)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:719)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:203)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:287)
	at com.mongodb.internal.operation.CommandOperationHelper.createReadCommandAndExecute(CommandOperationHelper.java:245)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:324)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:345)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:344)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:343)
	at com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:321)
	at com.mongodb.internal.operation.CommandOperationHelper.lambda$decorateReadWithRetries$3(CommandOperationHelper.java:192)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:332)
	at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:72)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:372)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:228)
	at dev.morphia.query.Query.iterator(Query.java:281)
	at dev.morphia.mapping.experimental.SingleReference.get(SingleReference.java:85)
	at dev.morphia.mapping.codec.references.ReferenceProxy.fetch(ReferenceProxy.java:80)
	at dev.morphia.mapping.codec.references.ReferenceProxy.invoke(ReferenceProxy.java:41)
	at Car$owner$$ReferenceProxy.unwrap(Unknown Source)
	at dev.morphia.mapping.codec.pojo.PropertyModel.getValue(PropertyModel.java:233)
	at dev.morphia.mapping.Mapper.getId(Mapper.java:231)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encodeId(ReferenceCodec.java:302)
	at dev.morphia.mapping.codec.references.ReferenceCodec.collectIdValues(ReferenceCodec.java:260)
	at dev.morphia.mapping.codec.references.ReferenceCodec.encode(ReferenceCodec.java:220)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.writeValue(EntityEncoder.java:134)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeValue(EntityEncoder.java:108)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encodeProperty(EntityEncoder.java:74)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.lambda$encode$0(EntityEncoder.java:52)
	at dev.morphia.aggregation.codecs.ExpressionHelper.document(ExpressionHelper.java:81)
	at dev.morphia.mapping.codec.pojo.EntityEncoder.encode(EntityEncoder.java:39)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.encode(MorphiaCodec.java:81)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:216)
	at com.mongodb.internal.connection.SplittablePayload$WriteRequestEncoder.encode(SplittablePayload.java:182)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at com.mongodb.internal.connection.BsonWriterHelper.writeDocument(BsonWriterHelper.java:77)
	at com.mongodb.internal.connection.BsonWriterHelper.writePayload(BsonWriterHelper.java:59)
	at com.mongodb.internal.connection.CommandMessage.encodeMessageBodyWithMetadata(CommandMessage.java:162)
	at com.mongodb.internal.connection.RequestMessage.encode(RequestMessage.java:136)
	at com.mongodb.internal.connection.CommandMessage.encode(CommandMessage.java:59)
	at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:358)
	at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)
	at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:719)
	at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)
	at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:203)
	at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)
	at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)
	at com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:295)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeCommand(MixedBulkWriteOperation.java:395)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.executeBulkWriteBatch(MixedBulkWriteOperation.java:259)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$2(MixedBulkWriteOperation.java:203)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$0(OperationHelper.java:345)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.lambda$withSourceAndConnection$1(OperationHelper.java:344)
	at com.mongodb.internal.operation.OperationHelper.withSuppliedResource(OperationHelper.java:370)
	at com.mongodb.internal.operation.OperationHelper.withSourceAndConnection(OperationHelper.java:343)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$execute$3(MixedBulkWriteOperation.java:188)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.lambda$decorateWriteWithRetries$0(MixedBulkWriteOperation.java:146)
	at com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:207)
	at com.mongodb.internal.operation.MixedBulkWriteOperation.execute(MixedBulkWriteOperation.java:77)
	at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:173)
	at com.mongodb.client.internal.MongoCollectionImpl.executeSingleWriteRequest(MongoCollectionImpl.java:1024)
	at com.mongodb.client.internal.MongoCollectionImpl.executeReplaceOne(MongoCollectionImpl.java:572)
	at com.mongodb.client.internal.MongoCollectionImpl.replaceOne(MongoCollectionImpl.java:555)
	at dev.morphia.DatastoreImpl$CollectionOperations.replaceOne(DatastoreImpl.java:928)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:729)
	at dev.morphia.DatastoreImpl.save(DatastoreImpl.java:627)
	at dev.morphia.Datastore.save(Datastore.java:527)
```

**To Reproduce**
 Run the following test with latest 2.3.x release:
```java
package dev.morphia.test;

import java.lang.reflect.Field;
import java.util.List;
import java.util.Map;

import com.mongodb.client.result.DeleteResult;

import dev.morphia.annotations.Reference;
import dev.morphia.mapping.codec.MorphiaCodecProvider;
import dev.morphia.query.filters.Filters;
import dev.morphia.test.mapping.ProxyTestBase;
import dev.morphia.test.models.TestEntity;

import org.bson.codecs.configuration.CodecProvider;
import org.bson.internal.ProvidersCodecRegistry;
import org.bson.types.ObjectId;
import org.testng.Assert;
import org.testng.annotations.Test;

@Test
public class TestTransactional extends ProxyTestBase {

    @Test
    public void testSaveAfterTransactionalFetch() throws Exception {
        checkForProxyTypes();
        checkForReplicaSet();

        // Preparations START
        // (1) Insert required entities into DB
        // (2) Clear any cached runtime data of datastore (entity models and their codecs)

        RootEntity root = new RootEntity();
        final ReferencedEntity ref = new ReferencedEntity();
        ref.setFoo("bar");

        root.r = ref;

        final ObjectId refId = getDs().save(ref).getId();
        final ObjectId rootId = getDs().save(root).getId();

        final Field entitiesCollField = getDs().getMapper().getClass().getDeclaredField("mappedEntities");
        entitiesCollField.setAccessible(true);

        final Map<?, ?> entitiesMap = (Map<?, ?>) entitiesCollField.get(getDs().getMapper());
        entitiesMap.clear();

        final Field entitiesCollField2 = getDs().getMapper().getClass().getDeclaredField("mappedEntitiesByCollection");
        entitiesCollField2.setAccessible(true);

        final Map<?, ?> entitiesMap2 = (Map<?, ?>) entitiesCollField2.get(getDs().getMapper());
        entitiesMap2.clear();

        final ProvidersCodecRegistry registry = (ProvidersCodecRegistry) getDs().getCodecRegistry();
        final Field codecProvidersField = registry.getClass().getDeclaredField("codecProviders");
        codecProvidersField.setAccessible(true);

        final List<CodecProvider> codecProviders = (List<CodecProvider>) codecProvidersField.get(registry);
        for (final CodecProvider provider : codecProviders) {
            if (provider instanceof MorphiaCodecProvider) {
                final MorphiaCodecProvider mcp = (MorphiaCodecProvider) provider;
                final Field f = MorphiaCodecProvider.class.getDeclaredField("codecs");
                f.setAccessible(true);

                ((Map<?, ?>) f.get(mcp)).clear();
            }
        }

        // Preparations END

        root = getDs().withTransaction((session) -> session.find(RootEntity.class)
                .filter(Filters.eq("r",
                        session.find(ReferencedEntity.class)
                                .filter(Filters.eq("_id", refId))
                                .first()))
                .first());

        final ReferencedEntity p = root.r;
        assertIsProxy(p);
        assertNotFetched(p);

        root.setBar("foo");
        getDs().save(root);

        Assert.assertEquals(root.getId(), rootId);
    }

    public static class RootEntity extends TestEntity {

        @Reference(idOnly = true, lazy = true)
        private ReferencedEntity r;

        private String bar;

        public void setR(ReferencedEntity r) {
            this.r = r;
        }

        public ReferencedEntity getR() {
            return r;
        }

        public String getBar() {
            return bar;
        }

        public void setBar(String bar) {
            this.bar = bar;
        }
    }

    public static class ReferencedEntity extends TestEntity {
        private String foo;

        public String getFoo() {
            return foo;
        }

        public void setFoo(String foo) {
            this.foo = foo;
        }
    }
}
```

Issue seem to be caused by `SingleReference` referencing a `MorphisSessionImpl` instance as datastore created by some former transaction.
As far as I understand the code, the datastore is passed from the codec to the `SingleReference`. Thus, the codec itself must have been initialized with the `MorphiaSessionImpl` instance.

**Expected behavior**
Unit test passes.

**Please complete the following information:**
 + Server Version: 6.0 
 + Driver Version: 4.9.0
 + Morphia Version: 2.3.7

**Comment by evanchooly** [comment]
This test actually works for me on the 2.3.x branch.

**Comment by h-arlt** [comment]
Did a fresh checkout from the 2.3.x branch and test still fails (as wanted and expected). Seems like you have some local modifications or commits not pushed to GH.

**Comment by evanchooly** [comment]
weird.  I just tried again this morning and it *did* fail so I'll dig in to it.  I'm a little worried the fix will be the deeper plumbing done in 2.4 which I'm hesitant to backport when a working version exists.  It's a largeish change that I'm trying to change in 3.x.

**Comment by evanchooly** [comment]
OK.  So here's what's happening.  You're fetching the root entity in a transaction/session and then using it outside that transaction.  Generally, that's ok.  But you have a lazy reference which is bound to that session which gets closed when the transaction ends.  So the fetch later fails because, well, the session is closed.  If you drop the laziness there, this works because everything is fetched in the moment.  Fetching lazy references outside the session is something that Morphia does not currently support.  JPA also breaks on such lazy relations and its various options for fixes all have their issues.  So at this point, I'm considering this "works as designed" and I'm going to remove it from this milestone.  I'll mark so that I can take another look in the 3.x which should have cleaner handling of such state.  Fwiw, I think this test will work in 2.4.3 mostly by accident so if you can't make this fetch eager, perhaps upgrading Morphia might help.

**Comment by evanchooly** [comment]
This won't work under the new state management either.  I think it's a fundamental misuse of sessions and shouldn't be allowed.

**Comment by h-arlt** [comment]
To be honest, I don't understand your last statement about session 
misuse. Maybe, I'm missing something.

When using lazy references, I as user of Morphia don't have exact 
control on when the reference is fetched and which session (if any) is 
used for the fetch. Thus, it's a perfectly valid use-case when 
transactions are allowed to be used (I assume so).

What about to model the session/transaction context more explicitly such 
that Morphia code can use it as the one and only access point to 
retrieve the proper datastore (or database operations) instance? Instead 
of keeping a reference to the datastore - or more precisely, the current 
datastore/session at time of instantiation by the codec - 
MorphiaReference can then use the session/transaction context to resolve 
the reference.

**Comment by evanchooly** [comment]
When you start a transaction, the `Datastore` you're using is actually a `MorphiaSession` which contains a reference to the `Session` in the driver.  This session gets closed at the end of the session gets closed at the end of the transaction and any attempts to use it after that result in the error you've encountered.  If you need those references to be lazy, all the work should be done within the transactional boundaries so that session remains open to do the fetch.  The codecs already track the `Datastore` associated with their lifecycle and so have that `Session` bound already.
