### ISSUE TITLE
META-INF/morphia-config.properties file not found

### ISSUE THREAD

**Issue by LuuckA21** [MorphiaOrg/morphia#2529]
**Describe the bug**
Configuration file not found, see error:

`java
dev.morphia.mapping.MappingException: The configuration file META-INF/morphia-config.properties could not be found.
	at dev.morphia.config.MorphiaConfigHelper.loadConfig(MorphiaConfigHelper.java:105) ~[?:?]
	at dev.morphia.config.MorphiaConfigHelper.loadConfig(MorphiaConfigHelper.java:92) ~[?:?]
	at dev.morphia.Morphia.createDatastore(Morphia.java:93) ~[?:?]
	at me.luucka.moria.DBManager.<init>(DBManager.java:21) ~[moria-0.0.1.jar:?]
	at me.luucka.moria.MoriaPlugin.onEnable(MoriaPlugin.java:9) ~[moria-0.0.1.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-164]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-164]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:640) ~[paper-1.20.1.jar:git-Paper-164]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:551) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-164]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-164]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

** Please complete the following information: **
 - Server Version: 6.0.6
 - Driver Version: 4.10.2
 - Morphia Version: 2.4.4

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

**Comment by evanchooly** [comment]
do you have that file in `src/main/resources/META-INF/morphia.properties` ?

**Comment by LuuckA21** [comment]
Yes I have
[Image](https://imgur.com/a/aJyH2Sjl)

**Comment by evanchooly** [comment]
If you're using maven or gradle, that file should get copied to your build dir (which is what's actually on the classpath at runtime).  Assuming maven, does `target/classes/META-INF/morphia-config.properties` exist?

**Comment by LuuckA21** [comment]
Yes exist
![Screenshot 2023-09-06 213335](https://github.com/MorphiaOrg/morphia/assets/50712503/f23f80d7-0576-4ebe-a882-de8ad57a09a6)
Same thing in jar file

**Comment by evanchooly** [comment]
There must be something off in your environment because that looks right to me.  
If you could put together a [reproducer](/morphiaorg/reproducer) I'd be happy to take a look and see.

**Comment by LuuckA21** [comment]
I don't understand what I have to do with reproducer

**Comment by evanchooly** [comment]
Create a new project using that as  template (there's a big green button for that) and then recreate the problem in that new project.  It uses maven so if you don't you'll want to recreate your environment as best you can.

**Comment by NOTiFYcouk** [comment]
Are you using: Morphia Version: 2.4.2? 

Say (https://morphia.dev/morphia/3.0/configuration.html):

"Configuration - Starting in Morphia 3.0, configuration will be driven via a configuration file rather than programmatic configuration."

**Comment by NOTiFYcouk** [comment]
I've migrated from:

`morphia-core-2.4.2.jar ->  morphia-core-3.0.0-20230725.035612-1.jar
`
Configuration: META-INF/morphia-config.properties 

See:  https://morphia.dev/morphia/3.0/configuration.html

Deployed: Sample config files Complete with defaults:

`NOTiFYmoto/src/main/java/META-INF/morphia-config.properties
`
Using Gradle 8.3: JAR:

`META-INF/morphia-config.properties

MongoDB 7.0.0 with:

```
morphia-core-3.0.0-20230725.035612-1.jar
bson-4.10.2.jar
mongodb-driver-core-4.10.2.jar
mongodb-driver-sync-4.10.2.jar
```

All works fine.

**Comment by evanchooly** [comment]
Thanks for confirming, @NOTiFYcouk  it should be `src/main/resources/` for the `META-INF/` folder but because works "accidentally" because of how maven/gradle work internally.  Does this help, @LuuckA21 ?
