### ISSUE TITLE
Can't find a codec for class java.time.LocalDateTime in legacy queries

### ISSUE THREAD

**Issue by dnfeitosa** [MorphiaOrg/morphia#2577]
**Describe the bug**

Legacy queries throw exception during encoding when the criteria include `java.time.LocalDateTime` values.

```
org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for CodecCacheKey{clazz=class java.time.LocalDateTime, types=null}.
	at org.bson.internal.ProvidersCodecRegistry.lambda$get$0(ProvidersCodecRegistry.java:87)
	at java.base/java.util.Optional.orElseGet(Optional.java:369)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:80)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:50)
	at org.bson.codecs.MapCodec.writeValue(MapCodec.java:146)
	at org.bson.codecs.MapCodec.encode(MapCodec.java:116)
	at org.bson.codecs.MapCodec.encode(MapCodec.java:44)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.DocumentCodec.writeValue(DocumentCodec.java:206)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:164)
	at org.bson.codecs.DocumentCodec.encode(DocumentCodec.java:44)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
	at org.bson.codecs.EncoderContext.encodeWithChildContext(EncoderContext.java:91)
	at org.bson.codecs.BsonDocumentCodec.writeValue(BsonDocumentCodec.java:139)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:118)
	at org.bson.codecs.BsonDocumentCodec.encode(BsonDocumentCodec.java:42)
	at com.mongodb.internal.connection.RequestMessage.addDocument(RequestMessage.java:210)
```

**To Reproduce**

Sample code: https://gist.github.com/dnfeitosa/eca14bca549c9e36a11c9cf7fec4a452

**Drivers**
 - Server Version: 5.0.21
 - Driver Version: Java 4.10.2
 - Morphia Version: 2.4.5

**Additional context**

I don't know if my debugging led to the right place/conclusion, but I found two possible reasons for this problem:
- Morphia's `HashMapCodec` internal codec registry is not complete, as it is [not properly initialized](https://github.com/MorphiaOrg/morphia/blob/master/core/src/main/java/dev/morphia/mapping/codec/MorphiaTypesCodecProvider.java#L35) 
- `LegacyQuery` generates a bson document with a different structure when compared to `MorphiaQuery`, and this structure triggers the faulty codec

Generated bson document (sorry for the XML!):
```
<org.bson.Document>
  <documentAsMap> <!-- LinkedHashMap -->
    <entry>
      <string>_id</string>
      <string>xxxxxx</string>
    </entry>
    <entry>
      <string>someDate</string>
      <map>  <!-- HashMap -->
        <entry>
          <string>$gte</string>
          <local-date-time>2023-09-29T12:12:09.104</local-date-time>
        </entry>
      </map>
    </entry>
  </documentAsMap>
</org.bson.Document>
```

When the Mongo driver re-encodes this document to generate the final query, it finds during the iteration process `HashMapCodec` as the codec for `someDate`'s field value and starts using it as the base codec. The value encoding process then looks for a `LocalDateTime` codec within `HashMapCodec`'s registry but fails to find it.

The reason for failing is that `HashMapCodec` was [initialized](https://github.com/MorphiaOrg/morphia/blob/master/core/src/main/java/dev/morphia/mapping/codec/MorphiaTypesCodecProvider.java#L35) using its [default constructor](https://github.com/mongodb/mongo-java-driver/blob/4.10.x/bson/src/main/org/bson/codecs/MapCodec.java#L58-L60), which used the default registry rather than having the more complete registry propagated to it.

**Comment by dnfeitosa** [comment]
Some additional context:

I tried not to use the legacy query but had issues with update some operations:

```
java.lang.UnsupportedOperationException: This is a legacy operation and is not supported on this version of the API.

	at dev.morphia.query.MorphiaQuery.legacyOperation(MorphiaQuery.java:92)
	at dev.morphia.query.Query.update(Query.java:505)
	at dev.morphia.Datastore.update(Datastore.java:618)
```

I've been slowly migrating some classes to the new query model since Morphia 2.2 but there are still ~120 classes to go. I'll get there, at some point :)

**Comment by evanchooly** [comment]
My mind tried very hard to make this a complicated fix but after some testing and poking and prodding, it turned out to be very simple.  🤷🏻

**Comment by evanchooly** [comment]
I just pushed 2.4.6 which should fix both your issues.
