### ISSUE TITLE
In a hashmap, if a key contains a dot, it is impossible to insert or update the object in MongoDB [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#268]
This is [Issue 268](http://code.google.com/p/morphia/issues/detail?id=268) moved from a Google Code project.
Added by 2011-04-13T10:21:36.000Z by [ah...@octo.com](http://code.google.com/u/102751115736814372280/).
Please review that bug for more context and additional comments, but update this bug.
 Closed (WontFix).

Original labels: Type-Defect, Priority-Low
### Original description

```
<b>What version are you using? (Morphia/Driver/MongoDB)</b>
Morphia : 0.99, Driver : 2.5, MongoDB : 1.6.5
<b>Please include a stack trace below:</b>
com.mongodb.MongoException: not okForStorage
    at com.mongodb.DBTCPConnector._checkWriteError(DBTCPConnector.java:141) ~[mongo-java-driver-2.5.jar:na]
    at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:162) ~[mongo-java-driver-2.5.jar:na]
    at com.mongodb.DBTCPConnector.say(DBTCPConnector.java:146) ~[mongo-java-driver-2.5.jar:na]
    at com.mongodb.DBApiLayer$MyCollection.update(DBApiLayer.java:335) ~[mongo-java-driver-2.5.jar:na]
    at com.mongodb.DBCollection.update(DBCollection.java:145) ~[mongo-java-driver-2.5.jar:na]
    at com.mongodb.DBCollection.update(DBCollection.java:157) ~[mongo-java-driver-2.5.jar:na]
```

**Comment by AaronLiang** [comment]
Any update?

**Comment by evanchooly** [comment]
If you are having a similar issue, please open a new a ticket with a test case to reproduce.  This one was closed two years ago.

**Comment by cteyton** [comment]
I encountered this issue : 

```
static class MyObjectWithMap {
        Map<String, String> map = Maps.newHashMap();
}
```

```
MyObjectWithMap obj = new MyObjectWithMap();
obj.map.put("keyOk", "OK");
getDs().save(obj);
obj.map.put("key.notOK", "notOK");
getDs().save(obj);
```

Generates this :
```
java.lang.IllegalArgumentException: Invalid BSON field name key.notOK
	 at org.bson.AbstractBsonWriter.writeName(AbstractBsonWriter.java:494)
	 at com.mongodb.DBObjectCodec.encodeMap(DBObjectCodec.java:219)
	 at com.mongodb.DBObjectCodec.writeValue(DBObjectCodec.java:198)
	 at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:128)
	 at com.mongodb.DBObjectCodec.encode(DBObjectCodec.java:61)
	 at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:48)
	 at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:27)
	 at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63)
	 at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29)
```
