### ISSUE TITLE
User-defined Codecs  [morphia.codec-provider] error

### ISSUE THREAD

**Issue by zhangdapen** [MorphiaOrg/morphia#2741]
**Describe the bug**
use morphia-config.properties to defined Codecs error
```java
Exception in thread "main" io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.lang.ClassCastException: class org.grand.codec.CustomProvider cannot be cast to class org.bson.codecs.Codec (org.grand.codec.CustomProvider and org.bson.codecs.Codec are in unnamed module of loader 'app')
	at io.smallrye.config.ConfigMappingProvider.mapConfigurationInternal(ConfigMappingProvider.java:1004)
	at io.smallrye.config.ConfigMappingProvider.lambda$mapConfiguration$3(ConfigMappingProvider.java:962)
	at io.smallrye.config.SecretKeys.doUnlocked(SecretKeys.java:28)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:962)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:91)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:699)
	at dev.morphia.config.MorphiaConfig.load(MorphiaConfig.java:75)
	at dev.morphia.config.MorphiaConfig.load(MorphiaConfig.java:53)
	at dev.morphia.Morphia.createDatastore(Morphia.java:77)
```
**To Reproduce**
META-INF/morphia-config.properties
`morphia.codec-provider =org.grand.codec.CustomProvider`
org.grand.codec.CustomProvider
```java
public class CustomProvider implements CodecProvider {
    @Override
    public <T> Codec<T> get(Class<T> aClass, CodecRegistry codecRegistry) {
        if (aClass == TableId.class) {
            return (Codec<T>) new TableIdCodec();
        }
        return null;
    }
}
```

org.grand.codec.TableIdCodec
```java
public class TableIdCodec implements Codec<TableId> {

    @Override
    public TableId decode(BsonReader reader, DecoderContext decoderContext) {
        return TableId.fromValue(reader.readString());
    }

    @Override
    public void encode(BsonWriter writer, TableId value, EncoderContext encoderContext) {
        if (value == null) {
            return;
        }
        writer.writeString(value.toString());
    }

    @Override
    public Class<TableId> getEncoderClass() {
        return TableId.class;
    }
}
```
org.grand.entry.TableId 
```java
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Accessors(chain = true)
public class TableId {

    public static final String FIELD_TABLE_ID = "table_id";

    private String appId;

    private String entryId;

    public static TableId fromValue(String value) {
        TableId tableId = new TableId();
        if (value != null) {
            String[] tableIdSplit = value.split("-");
            if (tableIdSplit.length == 2) {
                tableId.setAppId(tableIdSplit[0])
                        .setEntryId(tableIdSplit[1]);
            }
        }

        return tableId;
    }


    @Override
    public String toString() {
        return MessageFormat.format("{0}-{1}", getAppId(), getEntryId());
    }
}
```
org.grand.App
```java
    public static void main(String[] args) {
        Datastore datastore = Morphia.createDatastore(MongoClients.create("mongodb://127.0.0.1:27017"));
    }
```

** Please complete the following information: **
 - Server Version: 
 - Driver Version:  4.11.1
 - Morphia Version: 2.4.8

**Additional context**
Any example models, queries, and executable test cases you can supply will greatly help debugging your issue:

**Comment by zhangdapen** [comment]
No problem using `MapperOptions`

**Comment by evanchooly** [comment]
2.4.10 just went live.
