### ISSUE TITLE
Morphia Halts and Prints Old Creator Warning When Finding and Mapping to Class

### ISSUE THREAD

**Issue by danielmillar** [MorphiaOrg/morphia#3157]
**Describe the bug**
When attempting to retrieve the first document that matches a filter and map it to the `PlayerInfo` data class, the function halts execution and prints the following message to the console:
`[dev.morphia.mapping.InstanceCreatorFactoryImpl] using old creator approach: dev.danielmillar.exchanger.database.data.PlayerInfo`

**To Reproduce**
1. Execute the following code to retrieve and process documents of type `PlayerInfo` then return the first document:
```kotlin
val playerInfo = datastore.find(PlayerInfo::class.java).filter(Filters.eq("uuid", uuid)).first()
```
2. Observe that the function halts execution and logs the console message.

**Expected behavior**
The code should successfully retrieve and map the document to the PlayerInfo data class without halting execution or printing the console message.

**Information**
 - Server Version: 4.4.1
 - Driver Version: 4.11.2
 - Morphia Version: 2.4.14

**Additional context**
Link to original discord message: https://discord.com/channels/940011609047335002/940011609047335007/1265405579808079932

PlayerInfo Data Class:
```kotlin
@Entity(value = "playerinfo", useDiscriminator = false)
data class PlayerInfo(
    @Id
    val uuid: UUID,
    val firstJoin: Long = System.currentTimeMillis(),
    var lastJoin: Long = System.currentTimeMillis()
)
```

Example Code Snippet:
```kotlin
Exchanger.instance.logger.info("test point1")
val playerInfo = datastore.find(PlayerInfo::class.java).filter(Filters.eq("_id", uuid)).first()
Exchanger.instance.logger.info("test point2")
```
Outcome:
![image](https://github.com/user-attachments/assets/6ff15429-a1a6-4bf7-89b1-117d78dabef5)

**Comment by danielmillar** [comment]
Attached a debugger and ran through what is happening, seems like it's throwing a MappingException but this exception is never logged, "No suitable constructor found for type: <PlayerInfo Class>"

![image](https://github.com/user-attachments/assets/ff66827c-d06d-4ae6-bb0c-174d2f0f30f1)

Stacktrace:
```
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.internal.ConstructorCreator.getFullConstructor(ConstructorCreator.java:136)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.InstanceCreatorFactoryImpl.create(InstanceCreatorFactoryImpl.java:50)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.codec.pojo.EntityModel.getInstanceCreator(EntityModel.java:288)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.codec.pojo.EntityDecoder.getInstanceCreator(EntityDecoder.java:121)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:47)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:53)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)"
"Exchanger-1.0-SNAPSHOT-all.jar//org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)"
"Exchanger-1.0-SNAPSHOT-encodeThrowable:315, CompletableFuture (java.util.concurrent)
8 hidden framesall.jar//org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)"
"Exchanger-1.0-SNAPSHOT-all.jar//org.bson.internal.LazyCodec.decode(LazyCodec.java:53)"
"Exchanger-1.0-SNAPSHOT-all.jar//org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)"
"Exchanger-1.0-SNAPSHOT-all.jar//org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)"
"Exchanger-1.0-SNAPSHOT-all.jar//org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:48)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:567)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:461)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:372)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:765)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:209)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:299)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.createReadCommandAndExecute(SyncOperationHelper.java:273)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:325)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$0(SyncOperationHelper.java:127)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:322)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateReadWithRetries$12(SyncOperationHelper.java:292)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:333)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:73)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130)"
"Exchanger-1.0-SNAPSHOT-all.jar//com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:372)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:228)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:200)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:195)"
"Exchanger-1.0-SNAPSHOT-all.jar//dev.danielmillar.exchanger.database.PlayerInfoManager.loadPlayerInfo$lambda$0(PlayerInfoManager.kt:18)"
"java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)"
"java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)"
"java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387)"
"java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312)"
"java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843)"
"java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808)"
"java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188)"```

**Comment by danielmillar** [comment]
The stacktrace was never printed to console because the CompletableFuture I had the find() wrapped didn't print it on itself and I wasn't attempting to log any results either, so removing the CompletableFuture and now it prints the full complete stracktrace for the exeception.

Detailed Stacktrace:
```
dev.morphia.mapping.MappingException: No suitable constructor found for type: 'dev.danielmillar.exchanger.database.data.PlayerInfo'
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.internal.ConstructorCreator.getFullConstructor(ConstructorCreator.java:136) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.InstanceCreatorFactoryImpl.create(InstanceCreatorFactoryImpl.java:50) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.codec.pojo.EntityModel.getInstanceCreator(EntityModel.java:288) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.codec.pojo.EntityDecoder.getInstanceCreator(EntityDecoder.java:121) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:47) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:53) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:76) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/org.bson.internal.LazyCodec.decode(LazyCodec.java:53) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:48) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:567) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:461) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:372) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:114) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:765) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:76) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:209) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:115) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:83) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:74) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.connection.DefaultServer$OperationCountTrackingConnection.command(DefaultServer.java:299) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.createReadCommandAndExecute(SyncOperationHelper.java:273) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.FindOperation.lambda$execute$1(FindOperation.java:325) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$0(SyncOperationHelper.java:127) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.lambda$withSourceAndConnection$1(SyncOperationHelper.java:126) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.withSuppliedResource(SyncOperationHelper.java:152) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.withSourceAndConnection(SyncOperationHelper.java:125) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.FindOperation.lambda$execute$2(FindOperation.java:322) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.SyncOperationHelper.lambda$decorateReadWithRetries$12(SyncOperationHelper.java:292) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.async.function.RetryingSyncSupplier.get(RetryingSyncSupplier.java:67) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:333) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:73) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:153) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:130) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:90) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:372) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:228) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:200) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:195) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.danielmillar.exchanger.database.PlayerInfoManager.loadPlayerInfo(PlayerInfoManager.kt:17) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at Exchanger-1.0-SNAPSHOT-all.jar/dev.danielmillar.exchanger.listeners.AsyncPlayerPreJoinListener.onPlayerPreJoin(AsyncPlayerPreJoinListener.kt:14) ~[Exchanger-1.0-SNAPSHOT-all.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor60.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-91-3c8a7fe]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.callPlayerPreLoginEvents(ServerLoginPacketListenerImpl.java:367) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl.lambda$handleCustomQueryPacket$1(ServerLoginPacketListenerImpl.java:437) ~[paper-1.21.jar:1.21-91-3c8a7fe]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by UnfamousThomas** [comment]
Now that makes more sense, as mentioned in Discord, the main issue is like it said, missing empty constructor. From Morphia docs, here: https://morphia.dev/morphia/2.4/mapping.html.

Under Constructors it says that you either need a constructor with empty parameters, or a constructor which has the same number of arguments, with the names being the same, also need to add a configuration to maven/gradle for Kotlin potentially.

In theory data class should have a constructor with all parameters and same names, so I am guessing the issue is this:

"For this mapping to take place, the source must be compiled to include the parameters in the generated bytecode. With javac this is typically already configured by default. However, Kotlin users will likely need to configure their builds to include the appropriate option. For maven users, it’s as simple as adding one line to the Kotlin maven plugin <configuration>"

As said in the above docs.

Most likely that is the issue. I would read the Constructor part of the docs.

@evanchooly might be able to say more since I have not actually used Morphia with Kotlin, but to me that looks to be the issue.

**Comment by danielmillar** [comment]
@UnfamousThomas You are correct, seems like the way I was trying to pass `-java-parameters` to the compiler within my build gradle was incorrect therefore it never compiled with it. 

I went ahead and had a look at the Kotlin compiler docs again and managed to get it to pass correctly to the compiler. Now when I attempt to find and map, it does it successfully and doesn't throw any exceptions or warnings
