### ISSUE TITLE
Unable to update to Spring Boot 3.3.x

### ISSUE THREAD

**Issue by ctmay4** [MorphiaOrg/morphia#3158]
I have a application that has been using Morphia for many years. It has worked with no issues. However I recently tried to update from Spring Boot 3.2.x to 3.3.2 and the server will no longer start.

```
Caused by: java.lang.IncompatibleClassChangeError: class dev.morphia.mapping.codec.MorphiaMapCodec cannot inherit from final class org.bson.codecs.MapCodec
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at dev.morphia.mapping.codec.MorphiaTypesCodecProvider.<init>(MorphiaTypesCodecProvider.java:29)
	at dev.morphia.DatastoreImpl.buildRegistry(DatastoreImpl.java:157)
	at dev.morphia.DatastoreImpl.<init>(DatastoreImpl.java:114)
	at dev.morphia.Morphia.createDatastore(Morphia.java:54)
	at com.imsweb.seerapi.MorphiaConfiguration.datastore(MorphiaConfiguration.java:86)
	at com.imsweb.seerapi.MorphiaConfiguration$$SpringCGLIB$$0.CGLIB$datastore$0(<generated>)
	at com.imsweb.seerapi.MorphiaConfiguration$$SpringCGLIB$$FastClass$$1.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348)
	at com.imsweb.seerapi.MorphiaConfiguration$$SpringCGLIB$$0.datastore(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146)
	... 91 common frames omitted
```

This is the line is fails at:

```java
Datastore datastore = Morphia.createDatastore(MongoClients.create(uri), db,
        MapperOptions.builder()
                .discriminatorKey("className")
                .discriminator(DiscriminatorFunction.className())
                .build());
```

I looked at the migration notes (https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.3-Release-Notes) and did not see anything that seemed relevant. Anyone else having a similar issue?

- Spring Boot 3.3.2
- Morphia 2.4.14
- MongoDB driver: 5.0.1

**Comment by evanchooly** [comment]
Morphia is not currently compatible with the 5.0 driver.

**Comment by ctmay4** [comment]
That makes sense. I will try to downgrade the dependency in Maven. Not sure if Spring Boot will have an issue with that.

**Comment by evanchooly** [comment]
I've debated a driver-5-compatibility-only 2.15 release branch but I'm hesitant to add more maintenance/release burden just now.  If it keeps coming up, I'll have to consider it more strongly I guess.

**Comment by hu-chia** [comment]
Is there another way to handle this incompatibility issue but keep the latest mongodb-driver?
