### ISSUE TITLE
Could really use this being an OSGi bundle. [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#405]
This is [Issue 405](http://code.google.com/p/morphia/issues/detail?id=405) moved from a Google Code project.
Added by 2012-04-26T10:29:10.000Z by [JamiePBo...@gmail.com](http://code.google.com/u/116521312443600925653/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low
### Original description

```
<b>What version are you using? (Morphia/Driver/MongoDB)</b>
v 1.00-SNAPSHOT of Morphia.


This is a feature request really. I'm trying to use morphia with the Mongo OSGi bundle and it's making things really tricky. - Company going of the idea of using Morphia as a result. 

Personally I'm loving morphia and really want to get it working in an OSGi environment. - tks.
```

**Comment by gbivins** [comment]
Has this been integrated into morphia. I'm having trouble using it in my OSGi enviroment (felix).
At  runtime I'm getting:

org.osgi.framework.BundleException: Unresolved constraint in bundle org.mongodb.morphia [26]: Unable to resolve 26.0: missing requirement [26.0] osgi.wiring.package; (osgi.wiring.package=com.thoughtworks.proxy)
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:3974)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2037)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1291)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
	at java.lang.Thread.run(Thread.java:744)

**Comment by charalamposc** [comment]
Hello,

is this issue still alive? I wanted to report the same issue as the comment above from gbivins, but with a different container. I tried it with Liferay:

```
org.osgi.framework.BundleException: Could not resolve module: gr.open.opap.mongodb.service [550]_  Unresolved requirement: Import-Package: org.mongodb.morphia; version="[1.3.0,2.0.0)"_    -> Export-Package: org.mongodb.morphia; bundle-symbolic-name="org.mongodb.morphia"; bundle-version="1.3.2"; version="1.3.2"; uses:="com.mongodb,com.mongodb.client.model,org.mongodb.morphia.aggregation,org.mongodb.morphia.annotations,org.mongodb.morphia.dao,org.mongodb.morphia.mapping,org.mongodb.morphia.mapping.cache,org.mongodb.morphia.query"_       org.mongodb.morphia [544]_         Unresolved requirement: Import-Package: com.thoughtworks.proxy_ [Sanitized]
	at org.eclipse.osgi.container.Module.start(Module.java:429)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1582)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1562)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1533)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:242)
	at org.eclipse.osgi.container.Module.doStart(Module.java:566)
	at org.eclipse.osgi.container.Module.start(Module.java:434)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:172)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:421)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:115)
	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:409)
	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:255)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:585)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1794)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by evanchooly** [comment]
Given the age and niche interest in this, I'm going to close this.  Between testing and maintenance costs, I'm not seeing the value especially when things like Java 9 modularity are more pressing.  If there's actually active interest, this can be revisited.
