### ISSUE TITLE
Cursor not found using query with large result set, 0.99.1-SNAPSHOT [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#444]
This is [Issue 444](http://code.google.com/p/morphia/issues/detail?id=444) moved from a Google Code project.
Added by 2013-01-18T13:16:31.000Z by [giovanni...@gmail.com](http://code.google.com/u/115837631875185636894/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Defect, Priority-Low
### Original description

```
Exception in thread &quot;main&quot; com.mongodb.MongoException$CursorNotFound: cursor 0 not found on server localhost/127.0.0.1:27018
        at com.mongodb.DBApiLayer$Result.init(DBApiLayer.java:373)
        at com.mongodb.DBApiLayer$Result._advance(DBApiLayer.java:433)
        at com.mongodb.DBApiLayer$Result.hasNext(DBApiLayer.java:400)
        at com.mongodb.DBCursor._hasNext(DBCursor.java:464)
        at com.mongodb.DBCursor.hasNext(DBCursor.java:484)
        at com.google.code.morphia.query.MorphiaIterator.hasNext(MorphiaIterator.java:40)

I have a collection with a lot of data. So i fetch them, but after some time it throws the error above, even if there are other documents in the collection.

I'm using version 0.99.1-SNAPSHOT .
```

**Comment by PavithraRaghu** [comment]
how to solve the cursor not found issue ? can anyone help me

**Comment by Jimit09Gandhi** [comment]
> 

+1 If anyone knows it would be helpful to know it

**Comment by evanchooly** [comment]
This is a 10 year old closed bug.  If you're seeing a new issue please file a new bug with the info requested on the template.  If you're still using 0.99, you're a decade behind the curve and should upgrade today.
