### ISSUE TITLE
Support embedded lists of a generic type parameter

### ISSUE THREAD

**Issue by dklotz** [MorphiaOrg/morphia#552]
I tried to set up a class hierarchy like this:

``` java
public abstract class Status<T extends Item> {
  @Embedded(concreteClass = java.util.ArrayList.class)
  private List<T> items;

  // ...
}

public class EmailStatus extends Status<EmailItem> {
  // ...
}
```

But when trying to map this, I get a RuntimeException: "bad type, not parameterized...". I thought this was related to issue #80, which is fixed sind 0.99.1, and we are using 0.105, but it still doesn't work. Am I doing something wrong or is this just not supported?

Cheers, 
David

What version are you using? (Morphia/Driver/MongoDB)
Morphia 0.105, Driver 2.11.3, DB v2.4.7

Please include a stack trace below:
java.lang.RuntimeException: bad type, not parameterized...
    at org.mongodb.morphia.utils.ReflectionUtils.isPropertyType(ReflectionUtils.java:177)
    at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:104)
    at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:76)
    at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:194)
    at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:119)
    at org.mongodb.morphia.mapping.Mapper.addMappedClass(Mapper.java:152)
    at org.mongodb.morphia.Morphia.map(Morphia.java:64)
    at com.fileee.SomeTest.createMorphia(SynchronizationStatusTest.java:43)

**Comment by jbasrai** [comment]
Is there any known solution/workaround for this?

**Comment by evanchooly** [comment]
works in 2.0
