### ISSUE TITLE
java.lang.RuntimeException: Generic TypeVariable not supported!

### ISSUE THREAD

**Issue by seinecle** [MorphiaOrg/morphia#925]
Using:
mongo-java-driver-3.2.2.jar
and
morphia-1.1.1.jar

The code:

```
for (UserList userList: userLists){
   DBObject userListDbObj = SingletonLaunchDB.getMorphia().toDBObject(userList);
   SingletonLaunchDB.getMongo().save(userListDbObj);
}
```

Error trace:

```
Grave:   java.lang.RuntimeException: Generic TypeVariable not supported!
    at org.mongodb.morphia.mapping.MappedField.toClass(MappedField.java:616)
    at org.mongodb.morphia.mapping.EphemeralMappedField.getSubClass(EphemeralMappedField.java:84)
    at org.mongodb.morphia.mapping.EphemeralMappedField.<init>(EphemeralMappedField.java:39)
    at org.mongodb.morphia.mapping.MappedField.discoverType(MappedField.java:498)
    at org.mongodb.morphia.mapping.MappedField.discover(MappedField.java:465)
    at org.mongodb.morphia.mapping.MappedField.<init>(MappedField.java:93)
    at org.mongodb.morphia.mapping.MappedClass.discover(MappedClass.java:540)
    at org.mongodb.morphia.mapping.MappedClass.<init>(MappedClass.java:124)
    at org.mongodb.morphia.mapping.Mapper.getMappedClass(Mapper.java:431)
    at org.mongodb.morphia.DatastoreImpl.getWriteConcern(DatastoreImpl.java:1632)
    at org.mongodb.morphia.DatastoreImpl.save(DatastoreImpl.java:686)
```

**Comment by evanchooly** [comment]
can you post your entity source?

**Comment by Serializator** [comment]
The same exception gets thrown at me when I have the following and try to fetch an instance of `TestUser` from MongoDB with Morphia, and it hurts so much :-(.

```
@Entity(value = "users", noClassnameStored = true)
class User<T extends Meta> {

  @Embedded
  private Map<String, T> meta;
}
```

```
public class TestUser<TestMeta> {

}
```

Using MongoDB Java Driver 3.3.0 and Morphia 1.2.1.

**Comment by jvence** [comment]
+1

**Comment by peter7328matyas** [comment]
+1

**Comment by evanchooly** [comment]
I know this bug is old and the response is probably too late.  But this works on master though there are warnings about the `T` type on the `meta` field above.  Using 1.3.2/1.4.0 should resolve any issues.  If not, please file a new issue and I'll take a look.
