### ISSUE TITLE
StackOverflowException mapping to object with 3-dimensional array

### ISSUE THREAD

**Issue by daveehrenberger** [MorphiaOrg/morphia#926]
The entity in question (code below) has a data member which is a three dimensional array representing a GeoJSON polygon. Mapping from this entity to the database was no issue however when attempting to retrieve _from_ the DB I see the error below. 

I've tried using the Morphia Query interface (code below) and separately tried the BasicDBObject style of building the query in conjunction with a Morphia.fromDBObject() method but both result in the same error. 

Querying via the mongo console works fine, as does querying in code up to the point where I have a DBObject. 

Morphia: v1.1.1
JDK: v1.7.0_67
MongoDB: 3.2.1
Mongo Java Driver: 3.2.2

Stacktrace:

```
Exception in thread "main" java.lang.StackOverflowError
    at java.util.concurrent.atomic.AtomicReferenceArray.length(AtomicReferenceArray.java:115)
    at com.google.common.cache.LocalCache$Segment.getFirst(LocalCache.java:2708)
    at com.google.common.cache.LocalCache$Segment.getEntry(LocalCache.java:2715)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2184)
    at com.google.common.cache.LocalCache.get(LocalCache.java:3953)
    at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3957)
    at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4875)
    at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4881)
    at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
    at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:68)
    at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:990)
    at com.google.inject.internal.InjectorImpl.getMembersInjector(InjectorImpl.java:997)
    at com.google.inject.internal.InjectorImpl.injectMembers(InjectorImpl.java:983)
    at com.fs.core.dao.GuiceObjectFactory.performMemberInjection(GuiceObjectFactory.java:130)
    at com.fs.core.dao.GuiceObjectFactory.createList(GuiceObjectFactory.java:88)
    at org.mongodb.morphia.converters.IterableConverter.createNewCollection(IterableConverter.java:122)
    at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:32)
    at org.mongodb.morphia.converters.Converters.decode(Converters.java:85)
    at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:62)
    at org.mongodb.morphia.converters.Converters.decode(Converters.java:85)
    at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:62)
    at org.mongodb.morphia.converters.Converters.decode(Converters.java:85)
    at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:62)
    at org.mongodb.morphia.converters.Converters.decode(Converters.java:85)
    at org.mongodb.morphia.converters.IterableConverter.decode(IterableConverter.java:62)
```

and it continues on like that for many more lines.

Morphia Query code:

```
Query<MyClass> query = ds.createQuery( MyClass.class );
query.field( "bounds" ).intersects( GeoJson.point( latitudeValue, longitudeValue ));
return query.get(); // <-- Stacktrace
```

Mongo code:

```
double[] pos = new double[] { longitudeValue, latitudeValue };

BasicDBObject geoJsonPoint = new BasicDBObject();
geoJsonPoint.put( "type", "Point" );
geoJsonPoint.put( "coordinates", pos );

BasicDBObject geom = new BasicDBObject();
geom.put( "$geometry", geoJsonPoint );

BasicDBObject intersects = new BasicDBObject();
intersects.put( "$geoIntersects", geom );

BasicDBObject query = new BasicDBObject( "bounds", intersects );

DBObject obj = ds.getCollection( MyClass.class ).find( query ).next();
System.out.println(obj); // <-- This prints the correct JSON form
return morph.fromDBObject( ds, MyClass.class, obj ); // <-- Stacktrace
```

Models:

```
@Embedded
public abstract class GeoJSON
{
  public enum Type {
    Point, MultiPoint, LineString, MultiLineString, Polygon, MultiPolygon, GeometryCollection
  };

  protected Type type;

  public GeoJSON( Type type )
  {
    this.type = type;
  }
}

@Embedded
public class GeoJSONPolygon extends GeoJSON
{
  @Property
  protected double[][][] coordinates;

  public GeoJSONPolygon()
  {
    this( 0, 0 );
  }

  public GeoJSONPolygon( int numRows, int numColumns )
  {
    super( GeoJSON.Type.Polygon );

    this.coordinates = new double[1][numRows][numColumns];
  }
}

@Indexes({ @Index( fields = @Field( value = "bounds", type = IndexType.GEO2DSPHERE )) })
public abstract class BaseClass
{
  @Id
  protected ObjectId id;
  protected GeoJSONPolygon bounds;
  protected Short[][] dataPoints;
  ...
  public abstract int someAbstractMethod();
}

@Entity( "my_entity" )
public class MyClass extends BaseClass
{
  @Override
  public int someAbstractMethod()
  {
    // trivial return of static data
  }
}
```

**Comment by daveehrenberger** [comment]
And to clarify a few lines of the stacktrace that are in my company's domain, the `com.fs.core.dao.GuiceObjectFactory` is just taking returned the `List<?>` from Morphia's `ObjectFactory.createList(MappedField)` method and invoking Guice's `Injector.injectMembers()` on it. I just verified that the original `List<?>` objects from the `ObjectFactory` are all non-null but empty.

**Comment by daveehrenberger** [comment]
So in debugging further, the issue is not on the 2D array of data points (I originally assumed that was the culprit due to the large data set I had) but actually on the 3D array representing the GeoJSON polygon (title and description have been updated appropriately to reflect the true issue).

On a hunch I swapped out my local `GeoJSONPolygon` for Morphia's `Polygon` and that worked like a charm. I now have a workaround but unless I have an error in my `GeoJSONPolygon` model there may still be an issue worth investigating.

**Comment by evanchooly** [comment]
I'm happy to hear that using the Morphia types solved your problem.  I started looking into the original problem to see if there is indeed a bug somewhere in Morphia but I'm running in to problems recreating.  How are you creating your `MyClass` instances?  I get errors trying to save the dummy instances I'm creating.

**Comment by daveehrenberger** [comment]
I use a factory which simply news the correct base type (MyClass) and then the requesting code populates the fields with data, namely bounds and dataPoints.

What errors do you see?

**Comment by evanchooly** [comment]
aged away.
