### ISSUE TITLE
Aggregation Pipeline Can Not Map To Equivalent Class

### ISSUE THREAD

**Issue by ghost** [MorphiaOrg/morphia#974]
Morphia `1.2.1`, Mongo `3.2.6`

`Martian.java`

``` java
import org.bson.types.ObjectId;
import org.mongodb.morphia.annotations.Entity;
import org.mongodb.morphia.annotations.Id;

@Entity
public class Martian {
    @Id
    public ObjectId id;
    public String name;
}
```

`Human.java`

``` java
import org.bson.types.ObjectId;

public class Human {
    public ObjectId id;
    public String name;
}
```

`AggregationTest.java`

``` java
import java.util.Arrays;

import org.junit.Test;
import org.mongodb.morphia.Datastore;
import org.mongodb.morphia.Morphia;

import com.mongodb.MongoClient;
import com.mongodb.ServerAddress;

public class AggregationTest {
    @Test
    public void aggregationCanSerializeToValidClass() {
        MongoClient client = new MongoClient(Arrays.asList(new ServerAddress("192.168.99.100", 27017)));

        Morphia morphia = new Morphia();
        morphia.map(Martian.class);

        Datastore datastore = morphia.createDatastore(client, "test");

        Martian martian = new Martian();
        datastore.save(martian);

        Human human = datastore.createAggregation(Martian.class)
            .limit(1)
            .aggregate(Human.class)
            .next();

        client.dropDatabase("test");
        client.close();
    }
}
```

Stack trace failure

```
java.lang.ClassCastException: Martian cannot be cast to Human
    at AggregationTest.aggregationCanSerializeToValidClass(AggregationTest.java:26)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

Is it not possible for Morphia to map to another class which is not a database entity?
I've seen workarounds for this, e.g. using `com.mongodb.DB` to create an aggregation, then map to target class.

It seems like the documentation suggests [this is possible](http://mongodb.github.io/morphia/1.2/guides/aggregation/)

**Comment by evanchooly** [comment]
This is currently interfering with the polymorphic queries.  I'm going to defer this until after 2.0 while I consider options.
